<a href="https://colab.research.google.com/github/victorncg/projetos_mentoria/blob/main/An%C3%A1lise_Fundamentalista_com_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Este arquivo foi modificado na sessão de mentoria do dia 04/04

# **Análise Fundamentalista com Python**

Este notebook foi criado como material de suporte para um novo conteúdo para as redes: "5 fontes de dados fundamentalistas que você precisa conhecer para utilizar no Python"

*Parte deste conteúdo foi escrito com a ajuda do ChatGPT*

1. brfinance
2. pybacen
3. Alpha Vantage
4. Fundamentus
5. Finnhub

Aqui estão cinco bibliotecas em Python que você pode usar para obter dados fundamentalistas de ações:

yfinance: Esta biblioteca permite extrair dados históricos e em tempo real de ações e outros instrumentos financeiros da Yahoo Finance. Ela fornece dados fundamentais, como demonstrações financeiras, indicadores de valuation, dados de dividendos e muito mais.

Finnhub: Finnhub é uma API de dados financeiros que fornece dados em tempo real para ações, forex, criptomoedas e muito mais. É uma ótima fonte de dados fundamentalistas, fornecendo acesso a demonstrações financeiras, índices de valuation, dados de dividendos e muito mais.

Alpha Vantage: Alpha Vantage é outra API de dados financeiros que fornece dados em tempo real para ações, forex, criptomoedas e muito mais. Ele fornece acesso a dados fundamentais, como demonstrações financeiras, índices de valuation, dados de dividendos e muito mais.

Quandl: Quandl é uma plataforma de dados financeiros que oferece acesso a uma grande variedade de conjuntos de dados financeiros. Ele fornece acesso a dados fundamentais, como demonstrações financeiras, índices de valuation, dados de dividendos e muito mais.

pandas-datareader: pandas-datareader é uma biblioteca que permite extrair dados de várias fontes financeiras, incluindo Yahoo Finance, Google Finance e muitos outros. Ele permite acessar dados fundamentais, como demonstrações financeiras, índices de valuation, dados de dividendos e muito mais.

# 1. brfinancemm

In [ ]:
!pip install brfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting brfinance
  Downloading brfinance-0.0.9-py3-none-any.whl (10 kB)
Collecting aiohttp<4.0.0,>=3.6.2
  Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 22.9 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.9/dist-packages (from brfinance) (4.11.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from brfinance) (1.4.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (from brfinance) (4.9.2)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from brfinance) (2.27.1)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 1.1 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 14.1 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp<4.0.0,>=3.6.2->brfinance) (2.0.12)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp<4.0.0,>=3.6.2->brfinance) (22.2.0)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 9.5 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4->brfinance) (2.4)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas->brfinance) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas->brfinance) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas->brfinance) (2022.7.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->brfinance) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->brfinance) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->brfinance) (3.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas->brfinance) (1.16.0)
Installing collected packages: multidict, frozenlist, async-timeout, yarl, aiosignal, aiohttp, brfinance
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 brfinance-0.0.9 frozenlist-1.3.3 multidict-6.0.4 yarl-1.8.2

In [ ]:
from brfinance import CVMAsyncBackend
import pandas as pd
from datetime import datetime, date


cvm_httpclient = CVMAsyncBackend()

# Dict de códigos CVM para todas as empresas
cvm_codes = cvm_httpclient.get_cvm_codes()
print(cvm_codes)

{'025224': '2W ECOBANK S.A. (REGISTRO ATIVO)', '917581': '2W ENERGIA S.A. (REGISTRO ATIVO)', '021954': '3A COMPANHIA SECURITIZADORA (REGISTRO CANCELADO)', '050504': '3M COMPANY (REGISTRO ATIVO)', '025291': '3R PETROLEUM ÓLEO E GÁS S.A (REGISTRO ATIVO)', '908830': '3Z REALTY DESENVOLVIMENTO IMOBILIARIO S/A (REGISTRO ATIVO)', '016330': 'EM LIQUIDAÇÃO EXTRAJUDICIAL (REGISTRO ATIVO)', '016284': '524 PARTICIPACOES S.A. (REGISTRO ATIVO)', '016349': '525 PARTICIPAÇOES SA (REGISTRO CANCELADO)', '091154': 'RIO PARANA ENERGIA S/A (INATIVA) (REGISTRO CANCELADO)', '904110': 'A  GERADORA  ALUGUEL DE MAQUINAS S.A. (REGISTRO ATIVO)', '901082': 'A BODYTECH PARTICIPACOES S.A. (REGISTRO ATIVO)', '917521': 'A. ANGELONI & CIA LTDA (REGISTRO ATIVO)', '016802': 'A.P. PARTICIPAÇOES SA (REGISTRO CANCELADO)', '910141': 'AB CONCESSOES S.A. (REGISTRO ATIVO)', '900043': 'ABA PORTO PARTICIPACOES S/A (REGISTRO ATIVO)', '900068': 'ABAPORU PARTICIPACOES S/A (REGISTRO ATIVO)', '056464': 'ABB LTD (REGISTRO ATIVO)', '050512': 'ABBOTT LABORATORIES (REGISTRO ATIVO)', '051071': 'ABBVIE INC. (REGISTRO ATIVO)', '013307': 'ABC DADOS E INFORMATICA SA (REGISTRO CANCELADO)', '016934': 'ABC SUPERMERCADOS SA (REGISTRO CANCELADO)', '013005': 'ABC XTAL MICROELETRONICA SA (REGISTRO CANCELADO)', '900050': 'ABIMEX IMPORTACAO E EXPORTACAO S/A (REGISTRO ATIVO)', '055239': 'ABIOMED INC (REGISTRO ATIVO)', '015270': 'ABN AMRO ARRENDAMENTO MERCANTIL SA (REGISTRO CANCELADO)', '057762': 'ABN AMRO BANK N.V (REGISTRO ATIVO)', '050335': 'ABRDN PHYSICAL GOLD SHARES ETF (REGISTRO ATIVO)', '050327': 'ABRDN PHYSICAL SILVER SHARES ETF (REGISTRO ATIVO)', '909689': 'ABRIL COMUNICACOES S.A. (REGISTRO ATIVO)', '014370': 'ABRIL SA (REGISTRO CANCELADO)', '020206': 'ABYARA PLANEJAMENTO IMOBILIÁRIO S/A (REGISTRO CANCELADO)', '058980': 'ACADEMY SPORTS & OUTDOORS INC (REGISTRO ATIVO)', '000001': 'ACCELLERON INDUSTRIES LTD', '050857': 'ACCENTURE PLC (REGISTRO ATIVO)', '900076': 'ACECO TI S/A (REGISTRO ATIVO)', '903617': 'ACEF S.A. (REGISTRO ATIVO)', '915298': 'ACHE LABORATORIOS FARMACEUTICOS S.A. (REGISTRO ATIVO)', '026425': 'AÇO VERDE DO BRASIL S.A (REGISTRO ATIVO)', '000060': 'ACOPALMA CIA INDL ACOS V PALMA (REGISTRO CANCELADO)', '000078': 'ACOS ANHANGUERA (VILLARES) S/A (REGISTRO CANCELADO)', '000086': 'ACOS DO BRASIL SA IND E COM (REGISTRO CANCELADO)', '014508': 'AÇOS FINOS PIRATINI S/A (REGISTRO CANCELADO)', '010715': 'ACOS IPANEMA (VILLARES) SA (REGISTRO CANCELADO)', '000108': 'AÇOS VILLARES SA (REGISTRO CANCELADO)', '913996': 'ACQIO HOLDING PARTICIPACOES S.A. (REGISTRO ATIVO)', '000116': 'ACRINOR ACRILONITRILA DO NE SA (REGISTRO CANCELADO)', '020230': 'ACRUX SECURITIZADORA S/A (REGISTRO CANCELADO)', '093122': 'ACTION INVESTIMENTOS LTDA', '051500': 'ACTIVISION BLIZZARD INC (REGISTRO ATIVO)', '018040': 'ACTORI PARTICIPAÇÕES SA (REGISTRO CANCELADO)', '916986': 'AÇU PETROLEO S.A. (REGISTRO ATIVO)', '020940': 'AÇUCAR GUARANI S/A (REGISTRO CANCELADO)', '910893': 'AÇUCAREIRA QUATA S.A. (REGISTRO ATIVO)', '900092': 'MADEIRAS (REGISTRO ATIVO)', '059226': 'ADAPTHEALTH CORP (REGISTRO ATIVO)', '913574': 'ADECOAGRO VALE DO EVINHEMA S.A. (REGISTRO ATIVO)', '007625': 'ADEPAR ASSESSORIA ADM SERV SA (REGISTRO CANCELADO)', '000132': 'ADESENE ADESIVOS NO NORDESTE SA (REGISTRO CANCELADO)', '051519': 'ADOBE INC (REGISTRO ATIVO)', '000159': 'ADUBOS VIANNA SA INDUSTRIA E COMERCIO (REGISTRO CANCELADO)', '054380': 'ADVANCE AUTO PARTS INC (REGISTRO ATIVO)', '021725': 'ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A. (REGISTRO CANCELADO)', '052647': 'ADVANCED MICRO DEVICES INC (REGISTRO ATIVO)', '023396': 'AEGEA SANEAMENTO E PARTICIPAÇÕES S.A. (REGISTRO ATIVO)', '056472': 'AEGON NV (REGISTRO ATIVO)', '025283': 'AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA S/A (REGISTRO ATIVO)', '000167': 'AEROFOTO CRUZEIRO SA (REGISTRO CANCELADO)', '909226': ' VIRACOPOS S.A. (REGISTRO ATIVO)', '917252': 'AEROPORTOS DO NORDESTE DO BRASIL S.A. (REGISTRO ATIVO)', '025640': 'AES BRASIL ENERGIA S.A. (REGISTRO ATIVO)', '026174': 'AES BRASIL OPERAÇÕES S.A. (REGISTRO ATIVO)', '917471': 'AES CAJUINA AB1 HOLDINGS S.A. (REGISTRO ATIVO)', '053546': 'AES CORP (REGISTRO ATIVO)', '019313': 'AES ELPA SA (REGISTRO CANCELADO)', '913830': 'AES HOLDINGS BRASIL S.A. (REGISTRO ATIVO)', '018970': 'AES TIETE ENERGIA SA (REGISTRO ATIVO)', '018350': 'AES TIETE SA (REGISTRO CANCELADO)', '915702': 'AES TUCANO HOLDING II S.A. (REGISTRO ATIVO)', '018104': 'AETATIS SECURITIZADORA S.A. (REGISTRO CANCELADO)', '913434': 'AMAZONIA EMPRESA TRANSMISSORA DE ENERGIA (REGISTRO ATIVO)', '051462': 'AETNA INC. (REGISTRO ATIVO)', '052655': 'AFLAC INC (REGISTRO ATIVO)', '020150': 'AFLUENTE G&T DE ENERGIA ELÉTRICA S/A (REGISTRO CANCELADO)', '022179': 'AFLUENTE TRANSMISSÃO DE ENERGIA ELÉTRICA S/A (REGISTRO ATIVO)', '917582': 'AFYA PARTICIPAÇÕES S.A (REGISTRO ATIVO)', '917615': 'AG-08 PARTICIPACOES S.A. (REGISTRO ATIVO)', '912600': 'AGASUS S.A. (REGISTRO ATIVO)', '917561': 'AGE ADMINISTRAÇÃO E PARTICIPAÇÕES S/A (REGISTRO ATIVO)', '914655': 'AGEO LESTE S.A (REGISTRO ATIVO)', '911115': 'AGEO NORTE TERMINAIS E ARMAZENS GERAIS S/A (REGISTRO ATIVO)', '900118': 'AGEO TERMINAIS E ARMAZENS GERAIS S/A (REGISTRO ATIVO)', '012343': 'AGF BRASIL SEGUROS SA (REGISTRO CANCELADO)', '000175': 'AGGS INDS GRAFICAS SA (REGISTRO CANCELADO)', '053511': 'AGILENT TECHNOLOGIES INC (REGISTRO ATIVO)', '003921': 'AGIP DISTRIBUIDORA SA (REGISTRO CANCELADO)', '900167': 'AGIPLAN FINANCEIRA S/A CREDITO FINANCIAMENTO E INV (REGISTRO ATIVO)', '916023': 'AGORA SOL. EM TEC. DA INFORMACAO E COMUNICACAO SA (REGISTRO ATIVO)', '908913': 'AGORACRED S/A SOCIEDADE DE CREDITO FINANCIAMENTO E (REGISTRO ATIVO)', '020664': 'AGRA EMPREENDIMENTOS IMOBILIÁRIOS S/A (REGISTRO CANCELADO)', '000183': 'AGRALE SA (REGISTRO CANCELADO)', '021911': 'AGRE EMPREENDIMENTOS IMOBILIÁRIOS SA (REGISTRO CANCELADO)', '914499': 'AGRICOLA ALVORADA LTDA (REGISTRO ATIVO)', '000191': 'AGRILEASING SA ARREND MERC (REGISTRO CANCELADO)', '516147': 'AGRO INDÚSTRIAS DO VALE SÃO FRANCISCO S/A (REGISTRO ATIVO)', '092010': 'AGRO INVEST LTDA', '000205': 'AGRO PASTORIL CARIRI SA CARIRISA (REGISTRO CANCELADO)', '912709': 'AGRO TALENT PARTICIPACOES S/A (REGISTRO ATIVO)', '916205': 'AGROCERES MULTIMIX NUTRICAO ANIMAL LTDA (REGISTRO ATIVO)', '025658': 'AGROGALAXY PARTICIPAÇÕES S.A. (REGISTRO ATIVO)', '909713': 'AGROINDS DO VALE DO SAO FCO S/A-AGROVALE (REGISTRO ATIVO)', '519715': 'AGROINDUSTRIAL DE CEREAIS VERDES CAMPOS S.A. (REGISTRO ATIVO)', '519847': 'AGROINDUSTRIAL E PASTORIL NATIVA S.A. (REGISTRO ATIVO)', '518859': 'AGROINDUSTRIAL SAPUCAIA S.A. (REGISTRO SUSPENSO)', '511404': 'AGROINDUSTRIAL VERA CRUZ S.A. (REGISTRO SUSPENSO)', '503681': 'AGROPECUÁRIA MARANHENSE S.A.', '000221': 'AGRONORTE SA (REGISTRO CANCELADO)', '915314': 'AGROPASTORIL JOTABASSO LTDA. (REGISTRO ATIVO)', '509205': 'AGROISA', '518824': 'AGROPECUÁRIA ARAÇATUBA S.A.', '517763': 'AGROPECUÁRIA BAIXO AMAZONAS S.A. (REGISTRO ATIVO)', '519073': 'AGROPECUÁRIA BRASIL PALMEIRAS S.A. (REGISTRO ATIVO)', '511412': 'AGROPECUÁRIA DOIS IRMÃOS S.A. (REGISTRO ATIVO)', '519154': 'AGROPECUARIA FIO DE OURO S.A. (REGISTRO CANCELADO)', '519642': 'AGROPECUÁRIA FOGLIATELLI S.A. (REGISTRO ATIVO)', '519251': 'AGROPECUARIA PINGUIM S.A. (REGISTRO ATIVO)', '520080': 'AGROPECUÁRIA PONTAL DO PARANAITA S.A. (REGISTRO ATIVO)', '503878': 'AGROPECUÁRIA RICASTRO S.A. (REGISTRO ATIVO)', '519804': 'AGROPECUÁRIA RIO URUARÁ S.A. (REGISTRO ATIVO)', '520101': 'AGROPECUÁRIA SANTA RITA DO MARAJÓ S.A. (REGISTRO ATIVO)', '520640': 'AGROPECUARIA TAMAKAVY S.A. (REGISTRO ATIVO)', '000213': 'AGROPECUARIA TAMAKAVY SA', '900134': 'AGROVIA DO NORDESTE S.A. (REGISTRO ATIVO)', '911875': 'AGUA LIMPA ENERGIA S/A (REGISTRO ATIVO)', '916175': 'AGUA VERMELHA TRANSMISSORA DE ENERGIA S.A (REGISTRO ATIVO)', '901421': 'CONCESSIONARIA DE SERVICOS PUBL (REGISTRO ATIVO)', '900084': 'AGUAS DE CAMBORIU SANEAMENTO SPE S.A. (REGISTRO ATIVO)', '900142': 'AGUAS DE NITEROI S.A. (REGISTRO ATIVO)', '916730': 'AGUAS DE NOVA FRIBURGO LTDA. (REGISTRO ATIVO)', '900324': 'AGUAS DE PENHA SANEAMENTO SPE S.A. (REGISTRO ATIVO)', '900175': 'AGUAS DE SAO FRANCISCO DO SUL SPE S.A. (REGISTRO ATIVO)', '900480': 'AGUAS DE SINOP S A (REGISTRO ATIVO)', '904169': 'AGUAS DE TERESINA SANEAMENTO  SPE  S.A. (REGISTRO ATIVO)', '090727': '90416 (REGISTRO ATIVO)', '025615': 'ÁGUAS DE TERESINA SANEAMENTO SPE S.A. (REGISTRO ATIVO)', '900183': 'AGUAS DE TIMON SANEAMENTO S.A. (REGISTRO ATIVO)', '916722': 'AGUAS DO IMPERADOR S.A.', '900159': 'AGUAS DO PARAIBA S/A (REGISTRO ATIVO)', '026735': 'ÁGUAS DO RIO 1 SPE S.A. (REGISTRO ATIVO)', '026743': 'ÁGUAS DO RIO 4 SPE S.A. (REGISTRO ATIVO)', '917520': 'ÁGUAS DO SERTÃO S.A. (REGISTRO ATIVO)', '023442': 'ÁGUAS GUARIROBA S.A (REGISTRO ATIVO)', '917498': 'ÁGUIA BRANCA PARTICIPAÇÕES S.A. (REGISTRO ATIVO)', '021806': 'AGV HOLDING S/A (REGISTRO CANCELADO)', '009288': 'AIR LIQUIDE (REGISTRO CANCELADO)', '054399': 'AIR PRODUCTS & CHEMICALS INC (REGISTRO ATIVO)', '057193': 'AIRBNB INC (REGISTRO ATIVO)', '914671': 'AK 24 EMPREENDIMENTOS E PARTICIPAÇÕES S.A. (REGISTRO ATIVO)', '053554': 'AKAMAI TECHNOLOGIES INC (REGISTRO ATIVO)', '057770': 'AKZO NOBEL (REGISTRO ATIVO)', '017957': 'AL-CAR EMPREENDIMENTOS E PARTICIPAÇÕES S (REGISTRO CANCELADO)', '055247': 'ALASKA AIR GROUP INC (REGISTRO ATIVO)', '018074': 'ALBAE PARTICIPACOES SA (REGISTRO CANCELADO)', '013242': 'ALBATROZ SA (REGISTRO CANCELADO)', '054402': 'ALBEMARLE CORP (REGISTRO ATIVO)', '916846': 'ALBIOMA CODORA ENERGIA S.A. (REGISTRO ATIVO)', '917502': 'ALBIOMA SOLAR BRASIL LTDA (REGISTRO ATIVO)', '015067': 'ALCALIS RIO GRANDE DO NORTE SA (REGISTRO CANCELADO)', '000256': 'ALCAN ALUMINIO DO BRASIL SA (REGISTRO CANCELADO)', '000264': 'ALCOA ALUMINIO SA (REGISTRO CANCELADO)', '050113': 'ALCOA INC.', '913764': 'ALCOESTE BIOENERGIA FERNANDÓPOLIS S.A. (REGISTRO ATIVO)', '057983': 'ALCON INC (REGISTRO ATIVO)', '917179': 'ALDO COMPONENTES ELETRONICOS S/A (REGISTRO ATIVO)', '900209': 'ALESAT COMBUSTIVEIS  S/A (REGISTRO ATIVO)', '916130': 'ALEX ENERGIA PARTICIPACOES S.A.', '055255': 'ALEXANDRIA REAL ESTATE EQUITIES INC (REGISTRO ATIVO)', '052663': 'ALEXION PHARMACEUTICALS INC (REGISTRO ATIVO)', '009954': 'ALFA HOLDINGS S.A. (REGISTRO ATIVO)', '000272': 'ALFRED NORDESTE SA INDUSTRIA VESTUARIO (REGISTRO CANCELADO)', '000280': 'ALFRED SA COMERCIO DO VESTUARIO (REGISTRO CANCELADO)', '900217': 'ALGAR TECNOLOGIA E CONSULTORIA  S.A. (REGISTRO ATIVO)', '021032': 'ALGAR TELECOM S/A (REGISTRO ATIVO)', '904102': 'ALGAR TI CONSULTORIA S.A (REGISTRO ATIVO)', '900225': 'ALIANCA GERACAO DE ENERGIA S.A. (REGISTRO ATIVO)', '910992': 'ALIANCA TRANSPORTADORA DE GAS PARTICIPACOES S.A (REGISTRO ATIVO)', '021300': 'ALIANSCE SHOPPING CENTERS S/A (REGISTRO CANCELADO)', '022357': 'ALIANSCE SONAE SHOPPING CENTERS S.A. (REGISTRO ATIVO)', '052280': 'ALIBABA GROUP HOLDING LTD (REGISTRO ATIVO)', '053562': 'ALIGN TECHNOLOGY INC (REGISTRO ATIVO)', '018260': 'ALIMENTA PARTICIPAÇÕES E SERVIÇOS SA (REGISTRO CANCELADO)', '014079': 'ALIPAR ALIMENTOS E PARTS SA (REGISTRO CANCELADO)', '917569': 'ALISEO EMPREENDIMENTOS E PARTICIPACOES S.A. (REGISTRO ATIVO)', '018082': 'ALIUM PARTICIPAÇÕES SA (REGISTRO CANCELADO)', '520225': 'ALL FAMA INDUSTRIAL S.A. (REGISTRO ATIVO)', '055263': 'ALLEGION PLC (REGISTRO ATIVO)', '057789': 'ALLFUNDS GROUP (REGISTRO ATIVO)', '055271': 'ALLIANT ENERGY CORP (REGISTRO ATIVO)', '900233': 'ALLIED TECNOLOGIA S.A. (REGISTRO ATIVO)', '025330': 'ALLIED TECNOLOGIA S.A. (REGISTRO ATIVO)', '020850': 'ALLIS PARTICIPAÇÕES S.A. (REGISTRO CANCELADO)', '914200': 'ALLONDA AMBIENTAL PARTICIPAÇÕES S.A. (REGISTRO ATIVO)', '917362': 'ALLONDA AMBIENTAL SANEAMENTO S.A. (REGISTRO ATIVO)', '900258': 'ALLPARK EMPREENDIMENTOS PARTICIPACOES E SERVICOS S (REGISTRO ATIVO)', '024953': 'ALLPARK EMPREENDIMENTOS PARTICIPACOES SERVICOS S.A (REGISTRO ATIVO)', '053570': 'ALLSTATE CORP (REGISTRO ATIVO)', '000302': 'ALMEC INDUSTRIAS MECANICA SA (REGISTRO CANCELADO)', '026395': 'ALMEIDA JUNIOR SHOPPING CENTERS S.A. (REGISTRO ATIVO)', '900241': 'ALMEIDA JUNIOR SHOPPING CENTERS S.A. (REGISTRO ATIVO)', '055964': 'ALNYLAM PHARMACEUTICALS INC (REGISTRO ATIVO)', '010456': 'ALPARGATAS S.A. (REGISTRO ATIVO)', '000310': 'ALPART ALPA PARTICIPACOES SA (REGISTRO CANCELADO)', '022217': 'ALPER CONSULTORIA E CORRETORA DE SEGUROS S.A. (REGISTRO ATIVO)', '051268': 'ALPHABET INC. (REGISTRO ATIVO)', '025275': 'ALPHAVILLE S.A. (REGISTRO ATIVO)', '900472': 'ALPHAVILLE URBANISMO S/A. (REGISTRO ATIVO)', '000329': 'ALPINA BRASIL SA MAQ IMP AGRIC (REGISTRO CANCELADO)', '000337': 'ALPLAN SA IND COM CH MAD AGLOM (REGISTRO CANCELADO)', '911123': 'ALSOL ENERGIAS RENOVAVEIS S.A. (REGISTRO ATIVO)', '017310': 'AMER.LAT.TELEC.AVANÇADAS S/A (REGISTRO CANCELADO)', '018066': 'ALTERE SECURITIZADORA S.A. (REGISTRO ATIVO)', '055972': 'ALTERYX INC (REGISTRO ATIVO)', '027030': 'ALTHAIA S.A. INDÚSTRIA FARMACÊUTICA (REGISTRO ATIVO)', '916978': 'ALTHAIA S.A. INDÚSTRIA FARMACÊUTICA (REGISTRO ATIVO)', '093602': 'ALTHAIA S.A. INDÚSTRIA FARMACÊUTICA (NÃO CONCEDIDO) (REGISTRO NÃO CONCEDIDO)', '051438': 'ALTRIA GROUP, INC.', '051527': 'ALTRIA GROUP, INC. (REGISTRO ATIVO)', '023183': 'ALTUS SISTEMAS DE AUTOMAÇÃO S.A. (REGISTRO CANCELADO)', '900266': 'ALUBAM PARTICIPACOES S/A (REGISTRO ATIVO)', '917461': 'ALUBAR METAIS E CABOS S.A. (REGISTRO ATIVO)', '521019': 'ALUMAZON COMPONENTES DA AMAZONIA S.A. (REGISTRO ATIVO)', '000345': 'ALUMINIO EXTRUSAO LAMINACAO (REGISTRO CANCELADO)', '021490': 'ALUPAR INVESTIMENTO S/A (REGISTRO ATIVO)', '900274': 'ALUSA ENGENHARIA S.A. (REGISTRO ATIVO)', '000353': 'ALUSUD ALUMINIO DO SUL SA (REGISTRO CANCELADO)', '026433': 'ALVAREZ & MARSAL INVESTIMENTOS I S.A. (REGISTRO ATIVO)', '000361': 'AMADEO ROSSI SA MET MUNICOES (REGISTRO CANCELADO)', '024503': 'AMALFI EMPREENDIMENTOS E PARTICIPAÇÕES S.A (REGISTRO CANCELADO)', '900282': 'AMAM PARTICIPACOES SPE S.A. (REGISTRO ATIVO)', '016918': 'AMARANTE PARTICIPACOES SA (REGISTRO CANCELADO)', '900035': 'AMATA  S.A. (REGISTRO ATIVO)', '050202': 'AMAZON.COM, INC (REGISTRO ATIVO)', '913301': 'AMAZONAS GERAÇÃO E TRANSMISSÃO DE ENERGIA S.A. (REGISTRO ATIVO)', '000370': 'AMAZONAS PRODS P CALCADOS SA (REGISTRO CANCELADO)', '026930': 'AMAZONE FUN PARKS S.A. (REGISTRO ATIVO)', '017280': 'AMAZONIA CELULAR S/A (REGISTRO CANCELADO)', '520187': 'AMAZÔNIA GOLF HOTELARIA E TURISMO S/A (REGISTRO ATIVO)', '916862': 'AMAZONIA SOLAR SEC. DE CREDITOS FINANCEIROS (REGISTRO ATIVO)', '912170': 'AMBAR ENERGIA LTDA (REGISTRO ATIVO)', '915983': 'AMBAR URUGUAIANA ENERGIA S.A.', '057991': 'AMBARELLA INC (REGISTRO ATIVO)', '023264': 'AMBEV S.A. (REGISTRO ATIVO)', '909721': 'AMBIENT-SERV.AMBIENT.RIBEIRAO PRETO S.A. (REGISTRO ATIVO)', '914663': 'AMBIENTAL MS PANTANAL SPE S.A (REGISTRO ATIVO)', '916338': 'AMBIENTAL PARTICIPACOES S.A.', '024961': 'AMBIPAR PARTICIPACOES E EMPREENDIMENTOS S/A (REGISTRO ATIVO)', '911891': 'AMBIPAR PARTICIPACOES E EMPREENDIMENTOS S/A', '057398': 'AMC ENTERTAINMENT HOLDINGS INC (REGISTRO ATIVO)', '515523': 'AMCOR EMBALAGENS DA AMAZÔNIA S.A. (REGISTRO SUSPENSO)', '055980': 'AMCOR PLC (REGISTRO ATIVO)', '058009': 'AMDOCS LTD (REGISTRO ATIVO)', '059242': 'AMEDISYS INC (REGISTRO ATIVO)', '012750': 'AMELCO SA IND ELETRONICA (REGISTRO CANCELADO)', '053538': 'AMEREN CORP (REGISTRO ATIVO)', '000388': 'AMERICA DO SUL LEAS SA ARR MER (REGISTRO CANCELADO)', '056480': 'AMERICA MOVIL SAB DE CV (REGISTRO ATIVO)', '914077': 'AMERICA NET S.A. (REGISTRO ATIVO)', '051446': 'AMERICAN AIRLINES GROUP INC. (REGISTRO ATIVO)', '052671': 'AMERICAN ELECTRIC POWER CO INC (REGISTRO ATIVO)', '050300': 'AMERICAN EXPRESS COMPANY (REGISTRO ATIVO)', '051489': 'AMERICAN INTERNATIONAL GROUP INC. (REGISTRO ATIVO)', '053589': 'AMERICAN TOWER CORP (REGISTRO ATIVO)', '917658': 'CESSAO DE INFRAESTRUTUR (REGISTRO ATIVO)', '055280': 'AMERICAN WATER WORKS CO INC (REGISTRO ATIVO)', '020990': 'AMERICANAS S.A (REGISTRO ATIVO)', '015679': 'AMERICAS EMPRS ARTISTICOS SA (REGISTRO CANCELADO)', '016195': 'AMERICEL SA (REGISTRO CANCELADO)', '055298': 'AMERIPRISE FINANCIAL INC (REGISTRO ATIVO)', '054429': 'AMERISOURCEBERGEN CORP (REGISTRO ATIVO)', '054437': 'AMETEK INC (REGISTRO ATIVO)', '050482': 'AMGEN INC. (REGISTRO ATIVO)', '021172': 'AMIL PARTICIPAÇÕES S/A (REGISTRO CANCELADO)', '026476': 'AMMO VAREJO S.A. (REGISTRO ATIVO)', '053600': 'AMPHENOL CORP (REGISTRO ATIVO)', '003050': 'AMPLA ENERGIA E SERVICOS S.A. (REGISTRO ATIVO)', '020214': 'AMPLA INVESTIMENTOS E SERVIÇOS S/A (REGISTRO CANCELADO)', '058971': 'AMYRIS INC (REGISTRO ATIVO)', '052680': 'ANALOG DEVICES INC (REGISTRO ATIVO)', '058017': 'ANAPLAN INC (REGISTRO ATIVO)', '019259': 'ANCAR EMPREENDIMENTOS COMERCIAIS S/A (REGISTRO CANCELADO)', '015326': 'ANCAR SHOPPING SA (REGISTRO CANCELADO)', '000396': 'ANCORA COMERCIAL SA (REGISTRO CANCELADO)', '914051': 'ANDALI AS (REGISTRO ATIVO)', '051381': 'ANDEAVOR (REGISTRO ATIVO)', '000400': 'ANDERSON CLAYTON SA IND E COM (REGISTRO CANCELADO)', '900316': 'ANDORINHA ENERGIAS RENOVAVEIS S/A (REGISTRO ATIVO)', '019437': 'ANDRADE GUTIERREZ CONCESSOES SA (REGISTRO CANCELADO)', '912535': 'ANDRADE GUTIERREZ PARTICIPACOES S.A. (REGISTRO ATIVO)', '019062': 'ANDRADE GUTIERREZ PARTICIPAÇÕES SA (REGISTRO CANCELADO)', '900191': 'ANDRADE GUTIERREZ S/A (REGISTRO ATIVO)', '915108': 'ANEMUS WIND HOLDING S.A. (REGISTRO ATIVO)', '026832': 'ANEMUS WIND HOLDING S.A. (REGISTRO ATIVO)', '057754': 'ANGLO AMERICAN PLC (REGISTRO ATIVO)', '056529': 'ANGLOGOLD ASHANTI LTD (REGISTRO ATIVO)', '917517': 'ANGULO45 EMPREENDIMENTOS S.A (REGISTRO ATIVO)', '018961': 'ANHANGUERA EDUCACIONAL PARTICIPAÇÕES S.A. (REGISTRO CANCELADO)', '052620': 'ANHEUSER-BUSCH INBEV SA/NV (REGISTRO ATIVO)', '023248': 'ANIMA HOLDING S.A. (REGISTRO ATIVO)', '058025': 'ANNALY CAPITAL MANAGEMENT INC (REGISTRO ATIVO)', '012416': 'ANSON SA ENG FUND RECUPERACOES (REGISTRO CANCELADO)', '055301': 'ANSYS INC (REGISTRO ATIVO)', '052698': 'AO SMITH CORP (REGISTRO ATIVO)', '054445': 'AON PLC (REGISTRO ATIVO)', '917522': 'AOVS SISTEMAS DE INFORMÁTICA S.A. (REGISTRO ATIVO)', '052701': 'APA CORP (REGISTRO ATIVO)', '054453': 'APARTMENT INVESTMENT & MANAGEMENT CO (REGISTRO ATIVO)', '909697': 'APERAM INOX AMERICA DO SUL S.A. (REGISTRO ATIVO)', '914531': 'APOLLO 17 PARTICIPACOES S.A (REGISTRO ATIVO)', '000426': 'APOLO PRODUTOS DE ACO SA (REGISTRO CANCELADO)', '050024': 'APPLE INC. (REGISTRO ATIVO)', '052710': 'APPLIED MATERIALS INC (REGISTRO ATIVO)', '914325': 'APSEN FARMACEUTICA S.A. (REGISTRO ATIVO)', '059250': 'APTARGROUP INC (REGISTRO ATIVO)', '051535': 'APTIV PLC (REGISTRO ATIVO)', '917507': 'AQUA-FOZ AQUÁRIO DE FOZ DO IGUAÇU S.A. (REGISTRO ATIVO)', '900027': 'AQUA-RIO AQUARIO MARINHO DO RIO DE JANEIRO S/A (REGISTRO ATIVO)', '022101': 'AQUA-RIO S/A (REGISTRO CANCELADO)', '012564': 'AQUATEC QUIMICA SA (REGISTRO CANCELADO)', '021512': 'ÁQUILLA SECURITIZADORA S.A. (REGISTRO CANCELADO)', '000434': 'ARACRUZ CELULOSE S/A (REGISTRO CANCELADO)', '000485': 'ARAFERTIL SA (REGISTRO CANCELADO)', '000442': 'ARAGUAIA CIA INDL DE PROD ALIM', '013161': 'ARAGUAIA SA MIN RACOES FERTIL (REGISTRO CANCELADO)', '009806': 'ARAPUA IMPORTACAO COMERCIO SA (REGISTRO CANCELADO)', '018651': 'ARAUCÁRIA PARTICIPAÇÕES SA (REGISTRO CANCELADO)', '900357': 'ARAUCARIA SANEAMENTO S/A (REGISTRO ATIVO)', '014788': 'ARBRA SA (REGISTRO CANCELADO)', '003964': 'ARCELOR BRASIL S.A. (REGISTRO CANCELADO)', '050083': 'ARCELORMITTAL (REGISTRO ATIVO)', '002658': 'ARCELORMITTAL INOX BRASIL S.A. (REGISTRO CANCELADO)', '052728': 'ARCHER-DANIELS-MIDLAND CO (REGISTRO ATIVO)', '915967': 'ARCO INSURETECH S.A. (REGISTRO ATIVO)', '000507': 'ARCON SA IND ELETROMETALURGICA (REGISTRO CANCELADO)', '912063': 'ARCOS SANEAMENTO E PARTICIPACOES LTDA (REGISTRO ATIVO)', '910448': 'ARCOVERDE TRANSMISSÃO DE ENERGIA S.A. (REGISTRO ATIVO)', '016926': 'ARDOSIA PARTICIPACOES SA (REGISTRO CANCELADO)', '911883': 'AREIA ENERGIA S/A (REGISTRO ATIVO)', '000000': 'AREIAS BELAS AGRIC IRRIGADA S.A.- ABAISA           (REGISTRO ATIVO)', '914473': 'ARES 2 PARTICIPAÇÕES S.A. (REGISTRO ATIVO)', '058033': 'ARES MANAGEMENT CORP (REGISTRO ATIVO)', '914085': 'ARES ONE PARTICIPACOES S.A. (REGISTRO ATIVO)', '022349': 'AREZZO INDÚSTRIA E COMÉRCIO S.A. (REGISTRO ATIV

In [ ]:
# Dict de todas as categorias de busca disponíveis (Fato relevante, DFP, ITR, etc.)
categories = cvm_httpclient.get_consulta_externa_cvm_categories()
print(categories)

{'EST_-1': 'TODOS os Documentos Estruturados', 'EST_3': 'ITR - Informações Trimestrais', 'EST_2': 'FRE - Formulário de Referência', 'EST_11': 'Informe do Código de Governança', 'EST_1': 'FCA - Formulário Cadastral', 'EST_4': 'DFP - Demonstrações Financeiras Padronizadas', 'EST_6': 'Informe Trimestral de Securitizadora', 'EST_13': 'IAN - Informações Anuais', 'IPE_-1_-1_-1': 'TODOS os Documentos com Informações Eventuais', 'IPE_44_-1_-1': 'Acordo de Acionistas|TODOS|   TODAS', 'IPE_1_-1_-1': 'Assembleia|TODOS|   TODAS', 'IPE_1_-1_4': 'Assembleia|TODOS|   Ata', 'IPE_1_-1_54': 'Assembleia|TODOS|   Boletim de voto a distância', 'IPE_1_-1_28': 'Assembleia|TODOS|   Edital de Convocação', 'IPE_1_-1_61': 'Assembleia|TODOS|   Instrução de voto', 'IPE_1_-1_6': 'Assembleia|TODOS|   Justificação de Incorporação, Cisão ou Fusão', 'IPE_1_-1_44': 'Assembleia|TODOS|   Manual para participação', 'IPE_1_-1_52': 'Assembleia|TODOS|   Mapa consolidado de voto a distância', 'IPE_1_-1_51': 'Assembleia|TODOS|   Mapa do Depositário Central', 'IPE_1_-1_50': 'Assembleia|TODOS|   Mapa do Escriturador', 'IPE_1_-1_53': 'Assembleia|TODOS|   Mapa final de votação', 'IPE_1_-1_56': 'Assembleia|TODOS|   Mapa final de votação detalhado', 'IPE_1_-1_57': 'Assembleia|TODOS|   Mapa Final de Votação Sintético', 'IPE_1_-1_41': 'Assembleia|TODOS|   Material referente a pedidos públicos de procuração', 'IPE_1_-1_2': 'Assembleia|TODOS|   Proposta da Administração', 'IPE_1_-1_32': 'Assembleia|TODOS|   Proposta para a assembleia', 'IPE_1_-1_5': 'Assembleia|TODOS|   Protocolo de Incorporação, Cisão ou Fusão', 'IPE_1_-1_55': 'Assembleia|TODOS|   Protocolo e Justificação de Incorporação, Fusão ou Cisão', 'IPE_1_-1_3': 'Assembleia|TODOS|   Sumário das Decisões', 'IPE_1_98_-1': 'Assembleia|AGCRA|   TODAS', 'IPE_1_98_4': 'Assembleia|AGCRA|   Ata', 'IPE_1_98_28': 'Assembleia|AGCRA|   Edital de Convocação', 'IPE_1_98_32': 'Assembleia|AGCRA|   Proposta para a assembleia', 'IPE_1_98_3': 'Assembleia|AGCRA|   Sumário das Decisões', 'IPE_1_97_-1': 'Assembleia|AGCRI|   TODAS', 'IPE_1_97_4': 'Assembleia|AGCRI|   Ata', 'IPE_1_97_28': 'Assembleia|AGCRI|   Edital de Convocação', 'IPE_1_97_32': 'Assembleia|AGCRI|   Proposta para a assembleia', 'IPE_1_97_3': 'Assembleia|AGCRI|   Sumário das Decisões', 'IPE_1_5_-1': 'Assembleia|AGDEB|   TODAS', 'IPE_1_5_4': 'Assembleia|AGDEB|   Ata', 'IPE_1_5_28': 'Assembleia|AGDEB|   Edital de Convocação', 'IPE_1_5_61': 'Assembleia|AGDEB|   Instrução de voto', 'IPE_1_5_44': 'Assembleia|AGDEB|   Manual para participação', 'IPE_1_5_2': 'Assembleia|AGDEB|   Proposta da Administração', 'IPE_1_5_3': 'Assembleia|AGDEB|   Sumário das Decisões', 'IPE_1_1_-1': 'Assembleia|AGE|   TODAS', 'IPE_1_1_4': 'Assembleia|AGE|   Ata', 'IPE_1_1_54': 'Assembleia|AGE|   Boletim de voto a distância', 'IPE_1_1_28': 'Assembleia|AGE|   Edital de Convocação', 'IPE_1_1_6': 'Assembleia|AGE|   Justificação de Incorporação, Cisão ou Fusão', 'IPE_1_1_44': 'Assembleia|AGE|   Manual para participação', 'IPE_1_1_52': 'Assembleia|AGE|   Mapa consolidado de voto a distância', 'IPE_1_1_51': 'Assembleia|AGE|   Mapa do Depositário Central', 'IPE_1_1_50': 'Assembleia|AGE|   Mapa do Escriturador', 'IPE_1_1_53': 'Assembleia|AGE|   Mapa final de votação', 'IPE_1_1_56': 'Assembleia|AGE|   Mapa final de votação detalhado', 'IPE_1_1_57': 'Assembleia|AGE|   Mapa Final de Votação Sintético', 'IPE_1_1_41': 'Assembleia|AGE|   Material referente a pedidos públicos de procuração', 'IPE_1_1_2': 'Assembleia|AGE|   Proposta da Administração', 'IPE_1_1_5': 'Assembleia|AGE|   Protocolo de Incorporação, Cisão ou Fusão', 'IPE_1_1_55': 'Assembleia|AGE|   Protocolo e Justificação de Incorporação, Fusão ou Cisão', 'IPE_1_1_3': 'Assembleia|AGE|   Sumário das Decisões', 'IPE_1_4_-1': 'Assembleia|AGESP|   TODAS', 'IPE_1_4_4': 'Assembleia|AGESP|   Ata', 'IPE_1_4_54': 'Assembleia|AGESP|   Boletim de voto a distância', 'IPE_1_4_28': 'Assembleia|AGESP|   Edital de Convocação', 'IPE_1_4_44': 'Assembleia|AGESP|   Manual para participação', 'IPE_1_4_52': 'Assembleia|AGESP|   Mapa consolidado de voto a distância', 'IPE_1_4_50': 'Assembleia|AGESP|   Mapa do Escriturador', 'IPE_1_4_53': 'Assembleia|AGESP|   Mapa final de votação', 'IPE_1_4_56': 'Assembleia|AGESP|   Mapa final de votação detalhado', 'IPE_1_4_57': 'Assembleia|AGESP|   Mapa Final de Votação Sintético', 'IPE_1_4_41': 'Assembleia|AGESP|   Material referente a pedidos públicos de procuração', 'IPE_1_4_2': 'Assembleia|AGESP|   Proposta da Administração', 'IPE_1_4_3': 'Assembleia|AGESP|   Sumário das Decisões', 'IPE_1_2_-1': 'Assembleia|AGO|   TODAS', 'IPE_1_2_4': 'Assembleia|AGO|   Ata', 'IPE_1_2_54': 'Assembleia|AGO|   Boletim de voto a distância', 'IPE_1_2_28': 'Assembleia|AGO|   Edital de Convocação', 'IPE_1_2_44': 'Assembleia|AGO|   Manual para participação', 'IPE_1_2_52': 'Assembleia|AGO|   Mapa consolidado de voto a distância', 'IPE_1_2_51': 'Assembleia|AGO|   Mapa do Depositário Central', 'IPE_1_2_50': 'Assembleia|AGO|   Mapa do Escriturador', 'IPE_1_2_53': 'Assembleia|AGO|   Mapa final de votação', 'IPE_1_2_56': 'Assembleia|AGO|   Mapa final de votação detalhado', 'IPE_1_2_57': 'Assembleia|AGO|   Mapa Final de Votação Sintético', 'IPE_1_2_41': 'Assembleia|AGO|   Material referente a pedidos públicos de procuração', 'IPE_1_2_2': 'Assembleia|AGO|   Proposta da Administração', 'IPE_1_2_3': 'Assembleia|AGO|   Sumário das Decisões', 'IPE_1_3_-1': 'Assembleia|AGO/E|   TODAS', 'IPE_1_3_4': 'Assembleia|AGO/E|   Ata', 'IPE_1_3_54': 'Assembleia|AGO/E|   Boletim de voto a distância', 'IPE_1_3_28': 'Assembleia|AGO/E|   Edital de Convocação', 'IPE_1_3_6': 'Assembleia|AGO/E|   Justificação de Incorporação, Cisão ou Fusão', 'IPE_1_3_44': 'Assembleia|AGO/E|   Manual para participação', 'IPE_1_3_52': 'Assembleia|AGO/E|   Mapa consolidado de voto a distância', 'IPE_1_3_51': 'Assembleia|AGO/E|   Mapa do Depositário Central', 'IPE_1_3_50': 'Assembleia|AGO/E|   Mapa do Escriturador', 'IPE_1_3_53': 'Assembleia|AGO/E|   Mapa final de votação', 'IPE_1_3_56': 'Assembleia|AGO/E|   Mapa final de votação detalhado', 'IPE_1_3_57': 'Assembleia|AGO/E|   Mapa Final de Votação Sintético', 'IPE_1_3_41': 'Assembleia|AGO/E|   Material referente a pedidos públicos de procuração', 'IPE_1_3_2': 'Assembleia|AGO/E|   Proposta da Administração', 'IPE_1_3_5': 'Assembleia|AGO/E|   Protocolo de Incorporação, Cisão ou Fusão', 'IPE_1_3_55': 'Assembleia|AGO/E|   Protocolo e Justificação de Incorporação, Fusão ou Cisão', 'IPE_1_3_3': 'Assembleia|AGO/E|   Sumário das Decisões', 'IPE_56_-1_-1': 'Ato Homologatório emitido pelo Banco Central|TODOS|   TODAS', 'IPE_3_-1_-1': 'Aviso aos Acionistas|TODOS|   TODAS', 'IPE_3_103_-1': 'Aviso aos Acionistas|Adoção do processo de voto múltiplo|   TODAS', 'IPE_3_104_-1': 'Aviso aos Acionistas|Adoção do voto a distância|   TODAS', 'IPE_3_96_-1': 'Aviso aos Acionistas|Aumento de capital por subscrição privada deliberado em RCA|   TODAS', 'IPE_3_83_-1': 'Aviso aos Acionistas|Comunicado art.133 da Lei nº6.404/76|   TODAS', 'IPE_3_105_-1': 'Aviso aos Acionistas|Data prevista para a assembleia|   TODAS', 'IPE_3_84_-1': 'Aviso aos Acionistas|Outros avisos|   TODAS', 'IPE_3_106_-1': 'Aviso aos Acionistas|Solicitação de acionista para o Boletim de Voto|   TODAS', 'IPE_48_-1_-1': 'Aviso aos Debenturistas|TODOS|   TODAS', 'IPE_45_-1_-1': 'Balanço Social|TODOS|   TODAS', 'IPE_73_-1_-1': 'BDR Não Patrocinado - Descritivo Operacional do Programa|TODOS|   TODAS', 'IPE_9_-1_-1': 'Calendário de Eventos Corporativos|TODOS|   TODAS', 'IPE_91_-1_-1': 'Carta Anual de Governança Corporativa|TODOS|   TODAS', 'IPE_91_113_-1': 'Carta Anual de Governança Corporativa|Carta Anual de Governança Corporativa (art. 8º, VIII da Lei 13.303/16|   TODAS', 'IPE_91_114_-1': 'Carta Anual de Governança Corporativa|Carta Anual de Políticas Públicas (art. 8º, I da Lei 13.303/16)|   TODAS', 'IPE_91_115_-1': 'Carta Anual de Governança Corporativa|Carta consolidada de políticas públicas e governança corporativa (Decreto Federal 8.945/16)|   TODAS', 'IPE_74_-1_-1': 'Código de Conduta|TODOS|   TODAS', 'IPE_106_-1_-1': 'Comunicação sobre demandas societárias|TODOS|   TODAS', 'IPE_80_-1_-1': 'Comunicação sobre Transação entre Partes Relacionadas|TODOS|   TODAS', 'IPE_6_-1_-1': 'Comunicado ao Mercado|TODOS|   TODAS', 'IPE_6_-1_30': 'Comunicado ao Mercado|TODOS|   Declaração de Alienação de Participação Acionária Relevante', 'IPE_6_-1_29': 'Comunicado ao Mercado|TODOS|   Declaração de Aquisição de Participação Acionária Relevante', 'IPE_6_87_-1': 'Comunicado ao Mercado|Apresentações a analistas/agentes do mercado|   TODAS', 'IPE_6_51_-1': 'Comunicado ao Mercado|Aquisição/Alienação de Participação Acionária Relevante|   TODAS', 'IPE_6_51_30': 'Comunicado ao Mercado|Aquisição/Alienação de Participação Acionária Relevante|   Declaração de Alienação de Participação Acionária Relevante', 'IPE_6_51_29': 'Comunicado ao Mercado|Aquisição/Alienação de Participação Acionária Relevante|   Declaração de Aquisição de Participação Acionária Relevante', 'IPE_6_52_-1': 'Comunicado ao Mercado|Esclarecimentos Sobre Consultas CVM/BOVESPA|   TODAS', 'IPE_6_134_-1': 'Comunicado ao Mercado|Esclarecimentos sobre questionamentos da B3|   TODAS', 'IPE_6_112_-1': 'Comunicado ao Mercado|Esclarecimentos sobre questionamentos da CVM/B3|   TODAS', 'IPE_6_102_-1': 'Comunicado ao Mercado|Instalação, mudança ou dissolução do Comitê de Auditoria Estatutário|   TODAS', 'IPE_6_55_-1': 'Comunicado ao Mercado|Mudança de Auditor (art. 28, Instr. CVM nº308/99)|   TODAS', 'IPE_6_53_-1': 'Comunicado ao Mercado|Outros Comunicados Não Considerados Fatos Relevantes|   TODAS', 'IPE_10_-1_-1': 'Contratos com Partes Relacionadas|TODOS|   TODAS', 'IPE_98_-1_-1': 'Contratos de Indenidade|TODOS|   TODAS', 'IPE_98_118_-1': 'Contratos de Indenidade|Contratos de indenidade e aditivos|   TODAS', 'IPE_98_119_-1': 'Contratos de Indenidade|Outros documentos relacionados a contratos de indenidade|   TODAS', 'IPE_69_-1_-1': 'Convenção de grupos de sociedades|TODOS|   TODAS', 'IPE_84_-1_-1': 'Dados cadastrais de companhias incentivadas|TODOS|   TODAS', 'IPE_7_-1_-1': 'Dados Econômico-Financeiros|TODOS|   TODAS', 'IPE_7_-1_36': 'Dados Econômico-Financeiros|TODOS|   Demonstrações Financeiras com reconciliação para IFRS', 'IPE_7_-1_35': 'Dados Econômico-Financeiros|TODOS|   Demonstrações Financeiras com reconciliação para US GAAP', 'IPE_7_-1_34': 'Dados Econômico-Financeiros|TODOS|   Demonstrações Financeiras em IFRS', 'IPE_7_-1_33': 'Dados Econômico-Financeiros|TODOS|   Demonstrações Financeiras em US GAAP', 'IPE_7_-1_42': 'Dados Econômico-Financeiros|TODOS|   DFs Mercosul com reconciliação para IFRS', 'IPE_7_-1_38': 'Dados Econômico-Financeiros|TODOS|   Outros', 'IPE_7_56_-1': 'Dados Econômico-Financeiros|Balanço Social|   TODAS', 'IPE_7_57_-1': 'Dados Econômico-Financeiros|Demonstração do Valor Adicionado|   TODAS', 'IPE_7_88_-1': 'Dados Econômico-Financeiros|Demonstrações Financeiras Adicionais|   TODAS', 'IPE_7_37_-1': 'Dados Econômico-Financeiros|Demonstrações Financeiras Anuais Completas|   TODAS', 'IPE_7_42_-1': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   TODAS', 'IPE_7_42_36': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   Demonstrações Financeiras com reconciliação para IFRS', 'IPE_7_42_35': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   Demonstrações Financeiras com reconciliação para US GAAP', 'IPE_7_42_34': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   Demonstrações Financeiras em IFRS', 'IPE_7_42_33': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   Demonstrações Financeiras em US GAAP', 'IPE_7_42_42': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   DFs Mercosul com reconciliação para IFRS', 'IPE_7_42_38': 'Dados Econômico-Financeiros|Demonstrações Financeiras em Padrões Internacionais|   Outros', 'IPE_7_45_-1': 'Dados Econômico-Financeiros|Demonstrações Financeiras Especiais - Registro Inicial de Cia Aberta|   TODAS', 'IPE_7_46_-1': 'Dados Econômico-Financeiros|Demonstrações Financeiras Intermediárias|   TODAS', 'IPE_7_46_42': 'Dados Econômico-Financeiros|Demonstrações Financeiras Intermediárias|   DFs Mercosul com reconciliação para IFRS', 'IPE_7_20_-1': 'Dados Econômico-Financeiros|Laudo de Avaliação|   TODAS', 'IPE_7_63_-1': 'Dados Econômico-Financeiros|Notificação do agente fiduciário aos debenturistas|   TODAS', 'IPE_7_85_-1': 'Dados Econômico-Financeiros|Plano de Investimento|   TODAS', 'IPE_7_29_-1': 'Dados Econômico-Financeiros|Press-release|   TODAS', 'IPE_7_58_-1': 'Dados Econômico-Financeiros|Relatório Anual|   TODAS', 'IPE_7_86_-1': 'Dados Econômico-Financeiros|Relatório de Agência de Rating|   TODAS', 'IPE_7_30_-1': 'Dados Econômico-Financeiros|Relatório de Agente Fiduciário|   TODAS', 'IPE_7_43_-1': 'Dados Econômico-Financeiros|Relatório de Análise Gerencial|   TODAS', 'IPE_101_-1_-1': 'DF - Patrimônio separado|TODOS|   TODAS', 'IPE_78_-1_-1': 'Documentos de Oferta de Distribuição Pública|TODOS|   TODAS', 'IPE_78_-1_49': 'Documentos de Oferta de Distribuição Pública|TODOS|   Minuta de Prospecto Definitivo', 'IPE_78_-1_48': 'Documentos de Oferta de Distribuição Pública|TODOS|   Minuta de Prospecto Preliminar', 'IPE_78_-1_46': 'Documentos de Oferta de Distribuição Pública|TODOS|   Prospecto Definitivo', 'IPE_78_-1_45': 'Documentos de Oferta de Distribuição Pública|TODOS|   Prospecto Preliminar', 'IPE_78_-1_47': 'Documentos de Oferta de Distribuição Pública|TODOS|   Suplemento de Prospecto', 'IPE_78_89_-1': 'Documentos de Oferta de Distribuição Pública|Anúncio de Encerramento de Distribuição Pública|   TODAS', 'IPE_78_90_-1': 'Documentos de Oferta de Distribuição Pública|Anúncio de Início de Distribuição Pública|   TODAS', 'IPE_78_91_-1': 'Documentos de Oferta de Distribuição Pública|Aviso ao Mercado|   TODAS', 'IPE_78_92_-1': 'Documentos de Oferta de Distribuição Pública|Comunicação de Modificação de Oferta|   TODAS', 'IPE_78_101_-1': 'Documentos de Oferta de Distribuição Pública|Comunicado de encerramento de oferta com esforços restritos|   TODAS', 'IPE_78_100_-1': 'Documentos de Oferta de Distribuição Pública|Comunicado de início de oferta com esforços restritos|   TODAS', 'IPE_78_93_-1': 'Documentos de Oferta de Distribuição Pública|Edital de Leilão de Ações|   TODAS', 'IPE_78_94_-1': 'Documentos de Oferta de Distribuição Pública|Informações sobre o Programa de Distribuição Contínua|   TODAS', 'IPE_78_136_-1': 'Documentos de Oferta de Distribuição Pública|Lâmina de Oferta de Ações/Units|   TODAS', 'IPE_78_137_-1': 'Documentos de Oferta de Distribuição Pública|Lâmina de Oferta de Dívida|   TODAS', 'IPE_78_95_-1': 'Documentos de Oferta de Distribuição Pública|Prospecto de Distribuição Pública|   TODAS', 'IPE_78_95_49': 'Documentos de Oferta de Distribuição Pública|Prospecto de Distribuição Pública|   Minuta de Prospecto Definitivo', 'IPE_78_95_48': 'Documentos de Oferta de Distribuição Pública|Prospecto de Distribuição Pública|   Minuta de Prospecto Preliminar', 'IPE_78_95_46': 'Documentos de Oferta de Distribuição Pública|Prospecto de Distribuição Pública|   Prospecto Definitivo', 'IPE_78_95_45': 'Documentos de Oferta de Distribuição Pública|Prospecto de Distribuição Pública|   Prospecto Preliminar', 'IPE_78_95_47': 'Documentos de Oferta de Distribuição Pública|Prospecto de Distribuição Pública|   Suplemento de Prospecto', 'IPE_104_-1_-1': 'Documentos para análise da oferta pela B3|TODOS|   TODAS', 'IPE_104_120_-1': 'Documentos para análise da oferta pela B3|Comprovante de pagamento de taxa (B3)|   TODAS', 'IPE_104_131_-1': 'Documentos para análise da oferta pela B3|Comunicados e Declarações (B3)|   TODAS', 'IPE_104_132_-1': 'Documentos para análise da oferta pela B3|Contratos de distribuição, estabilização e outros (B3)|   TODAS', 'IPE_104_130_-1': 'Documentos para análise da oferta pela B3|Documento com marcas de revisão (B3)|   TODAS', 'IPE_104_123_-1': 'Documentos para análise da oferta pela B3|Requerimento à B3|   TODAS', 'IPE_102_-1_-1': 'Documentos para listagem de companhia na B3|TODOS|   TODAS', 'IPE_102_-1_38': 'Documentos para listagem de companhia na B3|TODOS|   Outros', 'IPE_102_120_-1': 'Documentos para listagem de companhia na B3|Comprovante de pagamento de taxa (B3)|   TODAS', 'IPE_102_130_-1': 'Documentos para listagem de companhia na B3|Documento com marcas de revisão (B3)|   TODAS', 'IPE_102_130_38': 'Documentos para listagem de companhia na B3|Documento com marcas de revisão (B3)|   Outros', 'IPE_102_121_-1': 'Documentos para listagem de companhia na B3|Outros documentos (B3)|   TODAS', 'IPE_102_123_-1': 'Documentos para listagem de companhia na B3|Requerimento à B3|   TODAS', 'IPE_85_-1_-1': 'Documentos para registro de companhia|TODOS|   TODAS', 'IPE_85_108_-1': 'Documentos para registro de companhia|Comprovante de pagamento de taxa|   TODAS', 'IPE_85_109_-1': 'Documentos para registro de companhia|Documento com marcas de revisão|   TODAS', 'IPE_85_49_-1': 'Documentos para registro de companhia|Outros documentos|   TODAS', 'IPE_85_107_-1': 'Documentos para registro de companhia|Requerimento à CVM e/ou à BM&FBOVESPA|   TODAS', 'IPE_103_-1_-1': 'Documentos para registro de companhia na CVM|TODOS|   TODAS', 'IPE_103_-1_60': 'Documentos para registro de companhia na CVM|TODOS|   Termo de Posse de Membro da Diretoria', 'IPE_103_127_-1': 'Documentos para registro de companhia na CVM|Documento com marcas de revisão - DFP|   TODAS', 'IPE_103_129_-1': 'Documentos para registro de companhia na CVM|Documento com marcas de revisão - Estatuto Social|   TODAS', 'IPE_103_126_-1': 'Documentos para registro de companhia na CVM|Documento com marcas de revisão - Formulário Cadastral|   TODAS', 'IPE_103_125_-1': 'Documentos para registro de companhia na CVM|Documento com marcas de revisão - Formulário de Referência|   TODAS', 'IPE_103_128_-1': 'Documentos para registro de companhia na CVM|Documento com marcas de revisão - ITR|   TODAS', 'IPE_103_122_-1': 'Documentos para registro de companhia na CVM|Outros documentos (CVM)|   TODAS', 'IPE_103_124_-1': 'Documentos para registro de companhia na CVM|Requerimento à CVM|   TODAS', 'IPE_103_135_-1': 'Documentos para registro de companhia na CVM|Termo de Posse|   TODAS', 'IPE_103_135_60': 'Documentos para registro de companhia na CVM|Termo de Posse|   Termo de Posse de Membro da Diretoria', 'IPE_86_-1_-1': 'Documentos para registro de oferta|TODOS|   TODAS', 'IPE_86_108_-1': 'Documentos para registro de oferta|Comprovante de pagamento de taxa|   TODAS', 'IPE_86_110_-1': 'Documentos para registro de oferta|Comunicados e Declarações|   TODAS', 'IPE_86_111_-1': 'Documentos para registro de oferta|Contratos de distribuição, estabilização e outros|   TODAS', 'IPE_86_109_-1': 'Documentos para registro de oferta|Documento com marcas de revisão|   TODAS', 'IPE_86_49_-1': 'Documentos para registro de oferta|Outros documentos|   TODAS', 'IPE_86_107_-1': 'Documentos para registro de oferta|Requerimento à CVM e/ou à BM&FBOVESPA|   TODAS', 'IPE_54_-1_-1': 'Escrituras e aditamentos de debêntures|TODOS|   TODAS', 'IPE_70_-1_-1': 'Estatuto Social|TODOS|   TODAS', 'IPE_4_-1_-1': 'Fato Relevante|TODOS|   TODAS', 'IPE_66_-1_-1': 'Formulário Cadastral - Em arquivo|TODOS|   TODAS', 'IPE_67_-1_-1': 'Formulário de Referência - Em arquivo|TODOS|   TODAS', 'IPE_67_61_-1': 'Formulário de Referência - Em arquivo|Atualizações previstas no art. 24 da IN480/09|   TODAS', 'IPE_67_60_-1': 'Formulário de Referência - Em arquivo|Formulário Completo|   TODAS', 'IPE_5_-1_-1': 'Informação Prestada às Bolsas Estrangeiras|TODOS|   TODAS', 'IPE_46_-1_-1': 'Informações Companhias em Falência|TODOS|   TODAS', 'IPE_46_68_-1': 'Informações Companhias em Falência|Causas e circunstâncias da falência|   TODAS', 'IPE_46_71_-1': 'Informações Companhias em Falência|Contas apresentadas ao final do processo de falência|   TODAS', 'IPE_46_

In [ ]:
# Realizando busca por Empresa
start_date = date(2020, 1, 1)
end_dt = date.today()
cvm_codes_list = ['21610'] # B3
category = ["EST_4", "EST_3", "IPE_4_-1_-1"] # Códigos de categoria para DFP, ITR e fatos relevantes
last_ref_date = False # Se "True" retorna apenas o último report no intervalo de datas

In [ ]:
# Busca
search_result = cvm_httpclient.get_consulta_externa_cvm_results(
    cod_cvm=cvm_codes_list,
    start_date=start_date,
    end_date=end_dt,
    last_ref_date=last_ref_date,
    category=category
    )

/usr/local/lib/python3.9/dist-packages/brfinance/responses.py:78: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  response_df = response_df.append(search_results_df)

In [ ]:
display(search_result)

,cod_cvm,empresa,categoria,tipo,especie,ref_date,data_entrega,status,version,modalidade,acoes,outros,view_url,numero_seq_documento,codigo_tipo_instituicao,numSequencia,numVersao,numProtocolo,descTipo
33,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",DFP - Demonstrações Financeiras Padronizadas,-,-,2022-12-31,2023-03-23 18:08:00,Ativo,2,RE,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,124513,1,124513,2,021610DFP311220220200124513-63,DFP
34,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",DFP - Demonstrações Financeiras Padronizadas,-,-,2022-12-31,2023-02-15 19:25:00,Inativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,123562,1,123562,1,021610DFP311220220100123562-67,DFP
32,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,"Projeções de despesas, investimentos, alavanca...",2022-12-08,2022-12-08 19:42:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,564307,1,1039577,IPE
31,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Programa de Recompra de Ações e Equity Swap -,2022-12-08,2022-12-08 19:40:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,564306,1,1039576,IPE
35,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2022-09-30,2022-11-10 18:53:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,121714,1,121714,1,021610ITR300920220100121714-75,ITR
30,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aquisição da Neurotech -,2022-11-09,2022-11-09 23:53:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,555416,1,1030685,IPE
36,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2022-06-30,2022-08-11 19:13:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,119633,1,119633,1,021610ITR300620220100119633-78,ITR
29,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Modificação de Projeções Divulgadas -,2022-08-11,2022-08-11 19:10:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,531755,1,1007021,IPE
28,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aprovação da sexta emissão de Debêntures simpl...,2022-07-25,2022-07-25 18:45:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,524817,1,1000083,IPE
27,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Modificação de Projeções Divulgadas -,2022-05-12,2022-05-12 19:15:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,505748,1,981014,IPE
37,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2022-03-31,2022-05-12 19:07:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,114979,1,114979,1,021610ITR310320220100114979-74,ITR
26,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Repactuação das Debêntures da 2ª Emissão -,2022-05-03,2022-05-03 18:06:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,500806,1,976072,IPE
38,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",DFP - Demonstrações Financeiras Padronizadas,-,-,2021-12-31,2022-03-17 19:11:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,112648,1,112648,1,021610DFP311220210100112648-71,DFP
25,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Conclusão da Aquisição da Neoway -,2021-12-23,2021-12-23 19:30:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,453536,1,928802,IPE
24,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,"Projeções de despesas, investimentos, alavanca...",2021-12-10,2021-12-10 09:26:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,449114,1,924380,IPE
23,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Programa de Recompra e Equity Swap -,2021-12-09,2021-12-09 21:27:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,448924,1,924190,IPE
39,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2021-09-30,2021-11-11 18:31:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,109787,1,109787,1,021610ITR300920210100109787-89,ITR
22,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aquisição da Neoway -,2021-10-19,2021-10-19 18:10:00,Ativo,2,RE,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,433144,2,908410,IPE
21,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aquisição da Neoway -,2021-10-19,2021-10-19 08:04:00,Inativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,433086,1,908352,IPE
20,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Tratativas para Aquisição da Neoway -,2021-10-14,2021-10-14 09:30:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,432197,1,907463,IPE
19,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Modificação de Projeções Divulgadas; Emissão d...,2021-09-15,2021-09-15 19:38:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,425986,1,901252,IPE
18,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Potencial Emissão de Títulos de Dívida Interna...,2021-09-10,2021-09-10 08:56:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,424654,1,899920,IPE
17,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Modificação de Projeções Divulgadas -,2021-08-11,2021-08-11 18:16:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,416988,1,892254,IPE
40,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2021-06-30,2021-08-11 18:02:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,107516,1,107516,1,021610ITR300620210100107516-76,ITR
16,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aprovação da quinta emissão de Debêntures simp...,2021-05-06,2021-05-06 18:36:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,388468,1,863731,IPE
41,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2021-03-31,2021-05-06 18:29:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,103505,1,103505,1,021610ITR310320210100103505-72,ITR
15,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Desdobramento de Ações; Novo Programa de Recom...,2021-03-04,2021-03-04 19:39:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,363549,1,838811,IPE
42,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",DFP - Demonstrações Financeiras Padronizadas,-,-,2020-12-31,2021-03-04 19:07:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,100673,1,100673,1,021610DFP311220200100100673-74,DFP
14,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Modelo Intermediário da Nova Política de Tarif...,2020-12-10,2020-12-10 18:31:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,339820,1,815082,IPE
13,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Divulgação das Projeções para 2021 -,2020-12-10,2020-12-10 18:28:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,339814,1,815076,IPE
12,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Contratação de Derivativos (Equity Swap) -,2020-12-10,2020-12-10 18:27:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,339806,1,815068,IPE
11,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Emissão de Debêntures -,2020-12-04,2020-12-04 18:13:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,337978,1,813240,IPE
10,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Modificação de Projeções Divulgadas -,2020-11-12,2020-11-12 18:47:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,332883,1,808145,IPE
43,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2020-09-30,2020-11-12 18:40:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,98354,1,98354,1,021610ITR300920200100098354-74,ITR
9,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Acordo em processo judicial e fim do litígio -,2020-08-31,2020-08-31 08:25:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,314050,1,789311,IPE
8,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aprovação da terceira emissão de Debêntures si...,2020-08-13,2020-08-13 20:07:00,Ativo,2,RE,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,309415,2,784674,IPE
44,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2020-06-30,2020-08-13 19:07:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,96054,1,96054,1,021610ITR300620200100096054-71,ITR
7,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,postergação do início do período de certificaç...,2020-08-13,2020-08-13 19:04:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,309368,1,784627,IPE
6,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Aprovação da terceira emissão de Debêntures si...,2020-08-13,2020-08-13 19:01:00,Inativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,309360,1,784619,IPE
5,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Revisão de projeções para 2020 -,2020-08-13,2020-08-13 18:56:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,309356,1,784615,IPE
4,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Reclassificação do Agio -,2020-06-03,2020-06-03 18:12:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,291111,1,766359,IPE
3,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Julgamento Agio - Caso 2008-2009 -,2020-05-18,2020-05-18 19:02:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,287404,1,762652,IPE
45,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",ITR - Informações Trimestrais,-,-,2020-03-31,2020-05-14 18:12:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,93114,1,93114,1,021610ITR310320200100093114-72,ITR
2,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,"Projeções de despesas, investimentos, captura ...",2020-05-14,2020-05-14 18:09:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,286743,1,761991,IPE
46,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",DFP - Demonstrações Financeiras Padronizadas,-,-,2019-12-31,2020-03-05 18:51:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmGerenciaPag...,91388,1,91388,1,021610DFP311220190100091388-85,DFP
1,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Programa de Recompra de Ações -,2020-03-05,2020-03-05 18:48:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,268202,1,743430,IPE
0,021610,"B3 S.A. - BRASIL, BOLSA, BALCÃO",Fato Relevante,-,Novas políticas de tarifas -,2020-01-02,2020-01-02 07:49:00,Ativo,1,AP,<i class='fi-page-search' id='VisualizarDocume...,NaN,https://www.rad.cvm.gov.br/ENET/frmExibirArqui...,NaN,NaN,253203,1,728443,IPE

In [ ]:
# Obter demonstrativos

reports_list = [
    'Balanço Patrimonial Ativo',
    'Balanço Patrimonial Passivo',
    'Demonstração do Resultado',
    'Demonstração do Resultado Abrangente',
    'Demonstração do Fluxo de Caixa',
    'Demonstração das Mutações do Patrimônio Líquido',
    'Demonstração de Valor Adicionado'] # Se None retorna todos os demonstrativos disponíveis.

# Filtro search_result para ITR e DFP apenas
search_result = search_result[
    (search_result['categoria']=="DFP - Demonstrações Financeiras Padronizadas") |
    (search_result['categoria']=="ITR - Informações Trimestrais")]

search_result = search_result[pd.to_numeric(search_result['numero_seq_documento'], errors='coerce').notnull()]

for index, row in search_result.iterrows():
    empresa = f"{row['cod_cvm']} - {cvm_codes[row['cod_cvm']]} - {row['numero_seq_documento']} - {row['codigo_tipo_instituicao']}"
    print("*" * 20, empresa, "*" * 20)
    
    reports = cvm_httpclient.get_report(row["numero_seq_documento"], row["codigo_tipo_instituicao"], reports_list=reports_list)
    for report in reports:
        print(report)
        reports[report]["cod_cvm"] = row["cod_cvm"]
        reports[report]["ref_date"] = row["ref_date"]
        reports[report]["numSequencia"] = row["numSequencia"]
        display(reports[report].head())

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 124513 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,47594773.0,Reais Mil,021610,2022-12-31,124513
1,1.01,Ativo Circulante,17129613.0,Reais Mil,021610,2022-12-31,124513
2,1.01.01,Caixa e Equivalentes de Caixa,2613794.0,Reais Mil,021610,2022-12-31,124513
3,1.01.02,Aplicações Financeiras,12290717.0,Reais Mil,021610,2022-12-31,124513
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,11085778.0,Reais Mil,021610,2022-12-31,124513

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,47594773.0,Reais Mil,021610,2022-12-31,124513
1,2.01,Passivo Circulante,9306446.0,Reais Mil,021610,2022-12-31,124513
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2022-12-31,124513
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2022-12-31,124513
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2022-12-31,124513

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,10110682.0,Reais Mil,021610,2022-12-31,124513
1,3.01.01,Segmento Listado,6578577.0,Reais Mil,021610,2022-12-31,124513
2,3.01.02,Segmento Balcão,1296363.0,Reais Mil,021610,2022-12-31,124513
3,3.01.03,Segmento Infraestrutura para Financiamento,441779.0,Reais Mil,021610,2022-12-31,124513
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",1789468.0,Reais Mil,021610,2022-12-31,124513

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,4226598,Reais Mil,021610,2022-12-31,124513
1,4.02,Outros Resultados Abrangentes,173586,Reais Mil,021610,2022-12-31,124513
2,4.02.01,Variação Cambial sobre Investimento em Control...,-3503,Reais Mil,021610,2022-12-31,124513
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,160589,Reais Mil,021610,2022-12-31,124513
4,4.02.03,Transferência de Instrumento de Hedge para o R...,-19801,Reais Mil,021610,2022-12-31,124513

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,9887484.0,Reais Mil,021610,2022-12-31,124513
1,6.01.01,Caixa Gerado nas Operações,7085400.0,Reais Mil,021610,2022-12-31,124513
2,6.01.01.01,Lucro Líquido do Exercício,4226598.0,Reais Mil,021610,2022-12-31,124513
3,6.01.01.02,Depreciação e Amortização,1056304.0,Reais Mil,021610,2022-12-31,124513
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,0.0,Reais Mil,021610,2022-12-31,124513

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-12-31,124513
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-12-31,124513
2,5.03,Saldos Iniciais Ajustados,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-12-31,124513
3,5.04,Transações de Capital com os Sócios,0.0,-3678067.0,-576705.0,-2281639.0,0.0,-6536411.0,0.0,-6536411.0,Reais Mil,021610,2022-12-31,124513
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-12-31,124513

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,10181334.0,Reais Mil,021610,2022-12-31,124513
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",10106187.0,Reais Mil,021610,2022-12-31,124513
2,7.01.02,Outras Receitas,4495.0,Reais Mil,021610,2022-12-31,124513
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,59429.0,Reais Mil,021610,2022-12-31,124513
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,11223.0,Reais Mil,021610,2022-12-31,124513

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 123562 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,47594773.0,Reais Mil,021610,2022-12-31,123562
1,1.01,Ativo Circulante,17129613.0,Reais Mil,021610,2022-12-31,123562
2,1.01.01,Caixa e Equivalentes de Caixa,2613794.0,Reais Mil,021610,2022-12-31,123562
3,1.01.02,Aplicações Financeiras,12290717.0,Reais Mil,021610,2022-12-31,123562
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,11085778.0,Reais Mil,021610,2022-12-31,123562

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,47594773.0,Reais Mil,021610,2022-12-31,123562
1,2.01,Passivo Circulante,9306446.0,Reais Mil,021610,2022-12-31,123562
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2022-12-31,123562
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2022-12-31,123562
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2022-12-31,123562

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,10110682.0,Reais Mil,021610,2022-12-31,123562
1,3.01.01,Segmento Listado,6578577.0,Reais Mil,021610,2022-12-31,123562
2,3.01.02,Segmento Balcão,1296363.0,Reais Mil,021610,2022-12-31,123562
3,3.01.03,Segmento Infraestrutura para Financiamento,441779.0,Reais Mil,021610,2022-12-31,123562
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",1789468.0,Reais Mil,021610,2022-12-31,123562

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,4226598,Reais Mil,021610,2022-12-31,123562
1,4.02,Outros Resultados Abrangentes,173586,Reais Mil,021610,2022-12-31,123562
2,4.02.01,Variação Cambial sobre Investimento em Control...,-3503,Reais Mil,021610,2022-12-31,123562
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,160589,Reais Mil,021610,2022-12-31,123562
4,4.02.03,Transferência de Instrumento de Hedge para o R...,-19801,Reais Mil,021610,2022-12-31,123562

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,9887484.0,Reais Mil,021610,2022-12-31,123562
1,6.01.01,Caixa Gerado nas Operações,7085400.0,Reais Mil,021610,2022-12-31,123562
2,6.01.01.01,Lucro Líquido do Exercício,4226598.0,Reais Mil,021610,2022-12-31,123562
3,6.01.01.02,Depreciação e Amortização,1056304.0,Reais Mil,021610,2022-12-31,123562
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,0.0,Reais Mil,021610,2022-12-31,123562

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-12-31,123562
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-12-31,123562
2,5.03,Saldos Iniciais Ajustados,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-12-31,123562
3,5.04,Transações de Capital com os Sócios,0.0,-3678067.0,-576705.0,-2281639.0,0.0,-6536411.0,0.0,-6536411.0,Reais Mil,021610,2022-12-31,123562
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-12-31,123562

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,10181334.0,Reais Mil,021610,2022-12-31,123562
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",10106187.0,Reais Mil,021610,2022-12-31,123562
2,7.01.02,Outras Receitas,4495.0,Reais Mil,021610,2022-12-31,123562
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,59429.0,Reais Mil,021610,2022-12-31,123562
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,11223.0,Reais Mil,021610,2022-12-31,123562

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 121714 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,48771393.0,Reais Mil,021610,2022-09-30,121714
1,1.01,Ativo Circulante,18498360.0,Reais Mil,021610,2022-09-30,121714
2,1.01.01,Caixa e Equivalentes de Caixa,4267671.0,Reais Mil,021610,2022-09-30,121714
3,1.01.02,Aplicações Financeiras,12481081.0,Reais Mil,021610,2022-09-30,121714
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,10851577.0,Reais Mil,021610,2022-09-30,121714

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,48771393.0,Reais Mil,021610,2022-09-30,121714
1,2.01,Passivo Circulante,11384975.0,Reais Mil,021610,2022-09-30,121714
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2022-09-30,121714
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2022-09-30,121714
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2022-09-30,121714

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2510567.0,Reais Mil,021610,2022-09-30,121714
1,3.01.01,Segmento Listado,1621472.0,Reais Mil,021610,2022-09-30,121714
2,3.01.02,Segmento Balcão,328847.0,Reais Mil,021610,2022-09-30,121714
3,3.01.03,Segmento Infraestrutura para Financiamento,110245.0,Reais Mil,021610,2022-09-30,121714
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",447203.0,Reais Mil,021610,2022-09-30,121714

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1029296,Reais Mil,021610,2022-09-30,121714
1,4.02,Outros Resultados Abrangentes,-52526,Reais Mil,021610,2022-09-30,121714
2,4.02.01,Variação Cambial sobre Investimento em Control...,4718,Reais Mil,021610,2022-09-30,121714
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,-58219,Reais Mil,021610,2022-09-30,121714
4,4.02.03,Transferência de Instrumento de Hedge para o R...,-6830,Reais Mil,021610,2022-09-30,121714

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,8064469.0,Reais Mil,021610,2022-09-30,121714
1,6.01.01,Caixa Gerado nas Operações,5471163.0,Reais Mil,021610,2022-09-30,121714
2,6.01.01.01,Lucro Líquido do Período,3222616.0,Reais Mil,021610,2022-09-30,121714
3,6.01.01.02,Depreciação e Amortização,798045.0,Reais Mil,021610,2022-09-30,121714
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,NaN,Reais Mil,021610,2022-09-30,121714

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-09-30,121714
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-09-30,121714
2,5.03,Saldos Iniciais Ajustados,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-09-30,121714
3,5.04,Transações de Capital com os Sócios,0.0,-2949071.0,-789295.0,-1559485.0,0.0,-5297851.0,0.0,-5297851.0,Reais Mil,021610,2022-09-30,121714
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-09-30,121714

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,7595058.0,Reais Mil,021610,2022-09-30,121714
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",7537591.0,Reais Mil,021610,2022-09-30,121714
2,7.01.02,Outras Receitas,4394.0,Reais Mil,021610,2022-09-30,121714
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,42120.0,Reais Mil,021610,2022-09-30,121714
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,10953.0,Reais Mil,021610,2022-09-30,121714

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 119633 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,47394318.0,Reais Mil,021610,2022-06-30,119633
1,1.01,Ativo Circulante,16721852.0,Reais Mil,021610,2022-06-30,119633
2,1.01.01,Caixa e Equivalentes de Caixa,2371543.0,Reais Mil,021610,2022-06-30,119633
3,1.01.02,Aplicações Financeiras,12803063.0,Reais Mil,021610,2022-06-30,119633
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,11253702.0,Reais Mil,021610,2022-06-30,119633

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,47394318.0,Reais Mil,021610,2022-06-30,119633
1,2.01,Passivo Circulante,10649128.0,Reais Mil,021610,2022-06-30,119633
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2022-06-30,119633
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2022-06-30,119633
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2022-06-30,119633

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2241632.0,Reais Mil,021610,2022-06-30,119633
1,3.01.01,Segmento Listado,1618716.0,Reais Mil,021610,2022-06-30,119633
2,3.01.02,Segmento Balcão,319054.0,Reais Mil,021610,2022-06-30,119633
3,3.01.03,Segmento Infraestrutura para Financiamento,110617.0,Reais Mil,021610,2022-06-30,119633
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",438314.0,Reais Mil,021610,2022-06-30,119633

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1092277,Reais Mil,021610,2022-06-30,119633
1,4.02,Outros Resultados Abrangentes,-241296,Reais Mil,021610,2022-06-30,119633
2,4.02.01,Variação Cambial sobre Investimento em Control...,14156,Reais Mil,021610,2022-06-30,119633
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,-265618,Reais Mil,021610,2022-06-30,119633
4,4.02.03,Transferência de Instrumento de Hedge para o R...,3249,Reais Mil,021610,2022-06-30,119633

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,5582034.0,Reais Mil,021610,2022-06-30,119633
1,6.01.01,Caixa Gerado nas Operações,3821005.0,Reais Mil,021610,2022-06-30,119633
2,6.01.01.01,Lucro Líquido do Período,2193320.0,Reais Mil,021610,2022-06-30,119633
3,6.01.01.02,Depreciação e Amortização,541955.0,Reais Mil,021610,2022-06-30,119633
4,6.01.01.03,Imposto de Renda e Contribuição Social Diferidos,409899.0,Reais Mil,021610,2022-06-30,119633

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-06-30,119633
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-06-30,119633
2,5.03,Saldos Iniciais Ajustados,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-06-30,119633
3,5.04,Transações de Capital com os Sócios,0.0,-2221029.0,-789295.0,-1075275.0,0.0,-4085599.0,0.0,-4085599.0,Reais Mil,021610,2022-06-30,119633
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-06-30,119633

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,5065179.0,Reais Mil,021610,2022-06-30,119633
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",5029824.0,Reais Mil,021610,2022-06-30,119633
2,7.01.02,Outras Receitas,1594.0,Reais Mil,021610,2022-06-30,119633
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,28539.0,Reais Mil,021610,2022-06-30,119633
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,5222.0,Reais Mil,021610,2022-06-30,119633

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 114979 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,50737250.0,Reais Mil,021610,2022-03-31,114979
1,1.01,Ativo Circulante,19784018.0,Reais Mil,021610,2022-03-31,114979
2,1.01.01,Caixa e Equivalentes de Caixa,2711499.0,Reais Mil,021610,2022-03-31,114979
3,1.01.02,Aplicações Financeiras,15857626.0,Reais Mil,021610,2022-03-31,114979
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,14534010.0,Reais Mil,021610,2022-03-31,114979

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,50737250.0,Reais Mil,021610,2022-03-31,114979
1,2.01,Passivo Circulante,11858196.0,Reais Mil,021610,2022-03-31,114979
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2022-03-31,114979
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2022-03-31,114979
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2022-03-31,114979

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2284699.0,Reais Mil,021610,2022-03-31,114979
1,3.01.01,Segmento Listado,1696750.0,Reais Mil,021610,2022-03-31,114979
2,3.01.02,Segmento Balcão,300734.0,Reais Mil,021610,2022-03-31,114979
3,3.01.03,Segmento Infraestrutura para Financiamento,109939.0,Reais Mil,021610,2022-03-31,114979
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",435700.0,Reais Mil,021610,2022-03-31,114979

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1101043,Reais Mil,021610,2022-03-31,114979
1,4.02,Outros Resultados Abrangentes,379084,Reais Mil,021610,2022-03-31,114979
2,4.02.01,Variação Cambial sobre Investimento em Control...,-17027,Reais Mil,021610,2022-03-31,114979
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,405345,Reais Mil,021610,2022-03-31,114979
4,4.02.03,Transferência do Instrumento de Hedge para o R...,-16473,Reais Mil,021610,2022-03-31,114979

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,1654899.0,Reais Mil,021610,2022-03-31,114979
1,6.01.01,Caixa Gerado nas Operações,1932151.0,Reais Mil,021610,2022-03-31,114979
2,6.01.01.01,Lucro Líquido do Período,1101043.0,Reais Mil,021610,2022-03-31,114979
3,6.01.01.02,Depreciação e Amortização,275945.0,Reais Mil,021610,2022-03-31,114979
4,6.01.01.03,Imposto de Renda e Contribuição Social Diferidos,379316.0,Reais Mil,021610,2022-03-31,114979

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-03-31,114979
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-03-31,114979
2,5.03,Saldos Iniciais Ajustados,12548655.0,7556201.0,2527217.0,0.0,-224168.0,22407905.0,11465.0,22419370.0,Reais Mil,021610,2022-03-31,114979
3,5.04,Transações de Capital com os Sócios,0.0,-989007.0,-789295.0,-302426.0,0.0,-2080728.0,0.0,-2080728.0,Reais Mil,021610,2022-03-31,114979
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2022-03-31,114979

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,2564587.0,Reais Mil,021610,2022-03-31,114979
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",2543123.0,Reais Mil,021610,2022-03-31,114979
2,7.01.02,Outras Receitas,1498.0,Reais Mil,021610,2022-03-31,114979
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,14385.0,Reais Mil,021610,2022-03-31,114979
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,5581.0,Reais Mil,021610,2022-03-31,114979

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 112648 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,52531769.0,Reais Mil,021610,2021-12-31,112648
1,1.01,Ativo Circulante,21095033.0,Reais Mil,021610,2021-12-31,112648
2,1.01.01,Caixa e Equivalentes de Caixa,2560516.0,Reais Mil,021610,2021-12-31,112648
3,1.01.02,Aplicações Financeiras,16576854.0,Reais Mil,021610,2021-12-31,112648
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,15517044.0,Reais Mil,021610,2021-12-31,112648

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,52531769.0,Reais Mil,021610,2021-12-31,112648
1,2.01,Passivo Circulante,12958993.0,Reais Mil,021610,2021-12-31,112648
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2021-12-31,112648
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2021-12-31,112648
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2021-12-31,112648

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,10288124.0,Reais Mil,021610,2021-12-31,112648
1,3.01.01,Segmento Listado,7097673.0,Reais Mil,021610,2021-12-31,112648
2,3.01.02,Segmento Balcão,1142744.0,Reais Mil,021610,2021-12-31,112648
3,3.01.03,Segmento Infraestrutura para Financiamento,476489.0,Reais Mil,021610,2021-12-31,112648
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",1387034.0,Reais Mil,021610,2021-12-31,112648

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,4717089,Reais Mil,021610,2021-12-31,112648
1,4.02,Outros Resultados Abrangentes,-302941,Reais Mil,021610,2021-12-31,112648
2,4.02.01,Variação Cambial sobre Investimento em Control...,4658,Reais Mil,021610,2021-12-31,112648
3,4.02.02,Valor dos Instrumentos de Hedges de Fluxo de C...,-203465,Reais Mil,021610,2021-12-31,112648
4,4.02.03,Transferência de Instrumento do Hedge para o R...,30524,Reais Mil,021610,2021-12-31,112648

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,3213723.0,Reais Mil,021610,2021-12-31,112648
1,6.01.01,Caixa Gerado nas Operações,7342860.0,Reais Mil,021610,2021-12-31,112648
2,6.01.01.01,Lucro Líquido do Exercício,4717089.0,Reais Mil,021610,2021-12-31,112648
3,6.01.01.02,Depreciação e Amortização,1057150.0,Reais Mil,021610,2021-12-31,112648
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,4114.0,Reais Mil,021610,2021-12-31,112648

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-12-31,112648
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-12-31,112648
2,5.03,Saldos Iniciais Ajustados,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-12-31,112648
3,5.04,Transações de Capital com os Sócios,0.0,-641486.0,-1198917.0,-4675799.0,0.0,-6516202.0,0.0,-6516202.0,Reais Mil,021610,2021-12-31,112648
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-12-31,112648

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,10435032.0,Reais Mil,021610,2021-12-31,112648
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",10103940.0,Reais Mil,021610,2021-12-31,112648
2,7.01.02,Outras Receitas,184184.0,Reais Mil,021610,2021-12-31,112648
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,149249.0,Reais Mil,021610,2021-12-31,112648
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,-2341.0,Reais Mil,021610,2021-12-31,112648

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 109787 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,54807451.0,Reais Mil,021610,2021-09-30,109787
1,1.01,Ativo Circulante,25600841.0,Reais Mil,021610,2021-09-30,109787
2,1.01.01,Caixa e Equivalentes de Caixa,3777045.0,Reais Mil,021610,2021-09-30,109787
3,1.01.02,Aplicações Financeiras,20196891.0,Reais Mil,021610,2021-09-30,109787
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,19265137.0,Reais Mil,021610,2021-09-30,109787

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,54807451.0,Reais Mil,021610,2021-09-30,109787
1,2.01,Passivo Circulante,15654356.0,Reais Mil,021610,2021-09-30,109787
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2021-09-30,109787
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2021-09-30,109787
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2021-09-30,109787

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2513222.0,Reais Mil,021610,2021-09-30,109787
1,3.01.01,Segmento Listado,1751542.0,Reais Mil,021610,2021-09-30,109787
2,3.01.02,Segmento Balcão,292436.0,Reais Mil,021610,2021-09-30,109787
3,3.01.03,Segmento Infraestrutura para Financiamento,123599.0,Reais Mil,021610,2021-09-30,109787
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",345352.0,Reais Mil,021610,2021-09-30,109787

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1176097,Reais Mil,021610,2021-09-30,109787
1,4.02,Outros Resultados Abrangentes,-125820,Reais Mil,021610,2021-09-30,109787
2,4.02.01,Variação Cambial sobre Investimento em Control...,5479,Reais Mil,021610,2021-09-30,109787
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,-93751,Reais Mil,021610,2021-09-30,109787
4,4.02.03,Transferência de Instrumento de Hedge para o R...,11501,Reais Mil,021610,2021-09-30,109787

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,-916604.0,Reais Mil,021610,2021-09-30,109787
1,6.01.01,Caixa Gerado nas Operações,5516672.0,Reais Mil,021610,2021-09-30,109787
2,6.01.01.01,Lucro Líquido do Período,3625435.0,Reais Mil,021610,2021-09-30,109787
3,6.01.01.02,Depreciação e Amortização,801416.0,Reais Mil,021610,2021-09-30,109787
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,0.0,Reais Mil,021610,2021-09-30,109787

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-09-30,109787
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-09-30,109787
2,5.03,Saldos Iniciais Ajustados,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-09-30,109787
3,5.04,Transações de Capital com os Sócios,0.0,-658916.0,-1988212.0,-2676736.0,0.0,-5323864.0,0.0,-5323864.0,Reais Mil,021610,2021-09-30,109787
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-09-30,109787

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,7957420.0,Reais Mil,021610,2021-09-30,109787
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",7672393.0,Reais Mil,021610,2021-09-30,109787
2,7.01.02,Outras Receitas,184184.0,Reais Mil,021610,2021-09-30,109787
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,99540.0,Reais Mil,021610,2021-09-30,109787
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,1303.0,Reais Mil,021610,2021-09-30,109787

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 107516 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,49530810.0,Reais Mil,021610,2021-06-30,107516
1,1.01,Ativo Circulante,19873683.0,Reais Mil,021610,2021-06-30,107516
2,1.01.01,Caixa e Equivalentes de Caixa,2065184.0,Reais Mil,021610,2021-06-30,107516
3,1.01.02,Aplicações Financeiras,16274057.0,Reais Mil,021610,2021-06-30,107516
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,15559387.0,Reais Mil,021610,2021-06-30,107516

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,49530810.0,Reais Mil,021610,2021-06-30,107516
1,2.01,Passivo Circulante,12507996.0,Reais Mil,021610,2021-06-30,107516
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2021-06-30,107516
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2021-06-30,107516
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2021-06-30,107516

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2417694.0,Reais Mil,021610,2021-06-30,107516
1,3.01.01,Segmento Listado,1807529.0,Reais Mil,021610,2021-06-30,107516
2,3.01.02,Segmento Balcão,280598.0,Reais Mil,021610,2021-06-30,107516
3,3.01.03,Segmento Infraestrutura para Financiamento,116753.0,Reais Mil,021610,2021-06-30,107516
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",342458.0,Reais Mil,021610,2021-06-30,107516

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1193311,Reais Mil,021610,2021-06-30,107516
1,4.02,Outros Resultados Abrangentes,-47637,Reais Mil,021610,2021-06-30,107516
2,4.02.01,Variação Cambial sobre Investimento em Control...,-8707,Reais Mil,021610,2021-06-30,107516
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,-9269,Reais Mil,021610,2021-06-30,107516
4,4.02.03,Transferência de Instrumento de Hedge para o R...,2422,Reais Mil,021610,2021-06-30,107516

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,1087095.0,Reais Mil,021610,2021-06-30,107516
1,6.01.01,Caixa Gerado nas Operações,3662369.0,Reais Mil,021610,2021-06-30,107516
2,6.01.01.01,Lucro Líquido do Período,2449338.0,Reais Mil,021610,2021-06-30,107516
3,6.01.01.02,Depreciação e Amortização,529159.0,Reais Mil,021610,2021-06-30,107516
4,6.01.01.03,Imposto de Renda e Contribuição Social Diferidos,550535.0,Reais Mil,021610,2021-06-30,107516

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-06-30,107516
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-06-30,107516
2,5.03,Saldos Iniciais Ajustados,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-06-30,107516
3,5.04,Transações de Capital com os Sócios,0.0,-677882.0,-1988212.0,-1495095.0,0.0,-4161189.0,0.0,-4161189.0,Reais Mil,021610,2021-06-30,107516
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-06-30,107516

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,5408141.0,Reais Mil,021610,2021-06-30,107516
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",5159464.0,Reais Mil,021610,2021-06-30,107516
2,7.01.02,Outras Receitas,183891.0,Reais Mil,021610,2021-06-30,107516
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,64596.0,Reais Mil,021610,2021-06-30,107516
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,190.0,Reais Mil,021610,2021-06-30,107516

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 103505 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,46194195.0,Reais Mil,021610,2021-03-31,103505
1,1.01,Ativo Circulante,16882731.0,Reais Mil,021610,2021-03-31,103505
2,1.01.01,Caixa e Equivalentes de Caixa,1536454.0,Reais Mil,021610,2021-03-31,103505
3,1.01.02,Aplicações Financeiras,14089062.0,Reais Mil,021610,2021-03-31,103505
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,13301353.0,Reais Mil,021610,2021-03-31,103505

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,46194195.0,Reais Mil,021610,2021-03-31,103505
1,2.01,Passivo Circulante,9503959.0,Reais Mil,021610,2021-03-31,103505
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2021-03-31,103505
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2021-03-31,103505
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2021-03-31,103505

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2396704.0,Reais Mil,021610,2021-03-31,103505
1,3.01.01,Segmento Listado,1892963.0,Reais Mil,021610,2021-03-31,103505
2,3.01.02,Segmento Balcão,269545.0,Reais Mil,021610,2021-03-31,103505
3,3.01.03,Segmento Infraestrutura para Financiamento,122104.0,Reais Mil,021610,2021-03-31,103505
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",327514.0,Reais Mil,021610,2021-03-31,103505

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1256027,Reais Mil,021610,2021-03-31,103505
1,4.02,Outros Resultados Abrangentes,-57835,Reais Mil,021610,2021-03-31,103505
2,4.02.01,Variação Cambial sobre Investimento em Control...,6040,Reais Mil,021610,2021-03-31,103505
3,4.02.02,Valor dos Instrumentos de Hedges de Fluxo de C...,-22364,Reais Mil,021610,2021-03-31,103505
4,4.02.03,Transferência de Instrumento do Hedge para o R...,4445,Reais Mil,021610,2021-03-31,103505

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,1708008.0,Reais Mil,021610,2021-03-31,103505
1,6.01.01,Caixa Gerado nas Operações,1870043.0,Reais Mil,021610,2021-03-31,103505
2,6.01.01.01,Lucro Líquido do Período,1256027.0,Reais Mil,021610,2021-03-31,103505
3,6.01.01.02,Depreciação e Amortização,264409.0,Reais Mil,021610,2021-03-31,103505
4,6.01.01.03,Imposto de Renda e Contribuição Social Diferidos,227413.0,Reais Mil,021610,2021-03-31,103505

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-03-31,103505
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-03-31,103505
2,5.03,Saldos Iniciais Ajustados,12548655.0,8198273.0,3684250.0,0.0,78773.0,24509951.0,11473.0,24521424.0,Reais Mil,021610,2021-03-31,103505
3,5.04,Transações de Capital com os Sócios,0.0,-340871.0,-798514.0,-222961.0,0.0,-1362346.0,0.0,-1362346.0,Reais Mil,021610,2021-03-31,103505
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2021-03-31,103505

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,2698269.0,Reais Mil,021610,2021-03-31,103505
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",2612126.0,Reais Mil,021610,2021-03-31,103505
2,7.01.02,Outras Receitas,55476.0,Reais Mil,021610,2021-03-31,103505
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,27264.0,Reais Mil,021610,2021-03-31,103505
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,3403.0,Reais Mil,021610,2021-03-31,103505

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 100673 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,46332783.0,Reais Mil,021610,2020-12-31,100673
1,1.01,Ativo Circulante,17101290.0,Reais Mil,021610,2020-12-31,100673
2,1.01.01,Caixa e Equivalentes de Caixa,1438420.0,Reais Mil,021610,2020-12-31,100673
3,1.01.02,Aplicações Financeiras,14068887.0,Reais Mil,021610,2020-12-31,100673
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,13249206.0,Reais Mil,021610,2020-12-31,100673

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,46332783.0,Reais Mil,021610,2020-12-31,100673
1,2.01,Passivo Circulante,9678085.0,Reais Mil,021610,2020-12-31,100673
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2020-12-31,100673
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2020-12-31,100673
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2020-12-31,100673

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,9327395.0,Reais Mil,021610,2020-12-31,100673
1,3.01.01,Segmento Listado,6441965.0,Reais Mil,021610,2020-12-31,100673
2,3.01.02,Segmento Balcão,1047028.0,Reais Mil,021610,2020-12-31,100673
3,3.01.03,Segmento Infraestrutura para Financiamento,425120.0,Reais Mil,021610,2020-12-31,100673
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",1134224.0,Reais Mil,021610,2020-12-31,100673

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,4150715.0,Reais Mil,021610,2020-12-31,100673
1,4.02,Outros Resultados Abrangentes,44393.0,Reais Mil,021610,2020-12-31,100673
2,4.02.01,Variação Cambial sobre Investimento em Control...,11461.0,Reais Mil,021610,2020-12-31,100673
3,4.02.02,Valor dos Instrumentos de Hedges de Fluxo de C...,66437.0,Reais Mil,021610,2020-12-31,100673
4,4.02.03,Transferência de Instrumento do Hedge para o R...,-65197.0,Reais Mil,021610,2020-12-31,100673

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,2753083.0,Reais Mil,021610,2020-12-31,100673
1,6.01.01,Caixa Gerado nas Operações,6281618.0,Reais Mil,021610,2020-12-31,100673
2,6.01.01.01,Lucro Líquido do Exercício,4150715.0,Reais Mil,021610,2020-12-31,100673
3,6.01.01.02,Depreciação e Amortização,1041301.0,Reais Mil,021610,2020-12-31,100673
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,80385.0,Reais Mil,021610,2020-12-31,100673

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-12-31,100673
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2020-12-31,100673
2,5.03,Saldos Iniciais Ajustados,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-12-31,100673
3,5.04,Transações de Capital com os Sócios,9000000.0,-9727105.0,-186236.0,-4152890.0,-8516.0,-5074747.0,-170.0,-5074917.0,Reais Mil,021610,2020-12-31,100673
4,5.04.01,Aumentos de Capital,9000000.0,-9000000.0,0.0,0.0,0.0,0.0,0.0,0.0,Reais Mil,021610,2020-12-31,100673

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,9463674.0,Reais Mil,021610,2020-12-31,100673
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",9048337.0,Reais Mil,021610,2020-12-31,100673
2,7.01.02,Outras Receitas,279058.0,Reais Mil,021610,2020-12-31,100673
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,142661.0,Reais Mil,021610,2020-12-31,100673
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,-6382.0,Reais Mil,021610,2020-12-31,100673

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 98354 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,45378408.0,Reais Mil,021610,2020-09-30,98354
1,1.01,Ativo Circulante,16127393.0,Reais Mil,021610,2020-09-30,98354
2,1.01.01,Caixa e Equivalentes de Caixa,1290332.0,Reais Mil,021610,2020-09-30,98354
3,1.01.02,Aplicações Financeiras,13346031.0,Reais Mil,021610,2020-09-30,98354
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,12667236.0,Reais Mil,021610,2020-09-30,98354

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,45378408.0,Reais Mil,021610,2020-09-30,98354
1,2.01,Passivo Circulante,8568387.0,Reais Mil,021610,2020-09-30,98354
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2020-09-30,98354
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2020-09-30,98354
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2020-09-30,98354

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,2535465.0,Reais Mil,021610,2020-09-30,98354
1,3.01.01,Segmento Listado,1682442.0,Reais Mil,021610,2020-09-30,98354
2,3.01.02,Segmento Balcão,262857.0,Reais Mil,021610,2020-09-30,98354
3,3.01.03,Segmento Infraestrutura para Financiamento,111564.0,Reais Mil,021610,2020-09-30,98354
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",290467.0,Reais Mil,021610,2020-09-30,98354

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1136496,Reais Mil,021610,2020-09-30,98354
1,4.02,Outros Resultados Abrangentes,19811,Reais Mil,021610,2020-09-30,98354
2,4.02.01,Variação Cambial sobre Investimento em Control...,1913,Reais Mil,021610,2020-09-30,98354
3,4.02.02,Valor dos Instrumentos de Hedge de Fluxo de Ca...,153,Reais Mil,021610,2020-09-30,98354
4,4.02.03,Transferência de Instrumento de Hedge para o R...,-5459,Reais Mil,021610,2020-09-30,98354

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,648908.0,Reais Mil,021610,2020-09-30,98354
1,6.01.01,Caixa Gerado nas Operações,4709172.0,Reais Mil,021610,2020-09-30,98354
2,6.01.01.01,Lucro Líquido do Período,3053376.0,Reais Mil,021610,2020-09-30,98354
3,6.01.01.02,Depreciação e Amortização,770488.0,Reais Mil,021610,2020-09-30,98354
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,67723.0,Reais Mil,021610,2020-09-30,98354

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-09-30,98354
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2020-09-30,98354
2,5.03,Saldos Iniciais Ajustados,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-09-30,98354
3,5.04,Transações de Capital com os Sócios,9000000.0,-9307974.0,-994247.0,-2219793.0,0.0,-3522014.0,-170.0,-3522184.0,Reais Mil,021610,2020-09-30,98354
4,5.04.01,Aumentos de Capital,9000000.0,-9000000.0,0.0,0.0,0.0,0.0,0.0,0.0,Reais Mil,021610,2020-09-30,98354

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,6879523.0,Reais Mil,021610,2020-09-30,98354
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",6594241.0,Reais Mil,021610,2020-09-30,98354
2,7.01.02,Outras Receitas,195450.0,Reais Mil,021610,2020-09-30,98354
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,95338.0,Reais Mil,021610,2020-09-30,98354
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,-5506.0,Reais Mil,021610,2020-09-30,98354

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 96054 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,44192558.0,Reais Mil,021610,2020-06-30,96054
1,1.01,Ativo Circulante,15139865.0,Reais Mil,021610,2020-06-30,96054
2,1.01.01,Caixa e Equivalentes de Caixa,966702.0,Reais Mil,021610,2020-06-30,96054
3,1.01.02,Aplicações Financeiras,13071603.0,Reais Mil,021610,2020-06-30,96054
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,12443420.0,Reais Mil,021610,2020-06-30,96054

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,44192558.0,Reais Mil,021610,2020-06-30,96054
1,2.01,Passivo Circulante,10865006.0,Reais Mil,021610,2020-06-30,96054
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2020-06-30,96054
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2020-06-30,96054
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2020-06-30,96054

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,1908332.0,Reais Mil,021610,2020-06-30,96054
1,3.01.01,Segmento Listado,1512047.0,Reais Mil,021610,2020-06-30,96054
2,3.01.02,Segmento Balcão,262784.0,Reais Mil,021610,2020-06-30,96054
3,3.01.03,Segmento Infraestrutura para Financiamento,78639.0,Reais Mil,021610,2020-06-30,96054
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",275594.0,Reais Mil,021610,2020-06-30,96054

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,891759,Reais Mil,021610,2020-06-30,96054
1,4.02,Outros Resultados Abrangentes,61881,Reais Mil,021610,2020-06-30,96054
2,4.02.01,Variação Cambial sobre Investimento em Control...,3166,Reais Mil,021610,2020-06-30,96054
3,4.02.02,Valor dos Instrumentos de Hedges de Fluxo de C...,49938,Reais Mil,021610,2020-06-30,96054
4,4.02.03,Transferência para o Resultado de Instrumento ...,-37707,Reais Mil,021610,2020-06-30,96054

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,1316508.0,Reais Mil,021610,2020-06-30,96054
1,6.01.01,Caixa Gerado nas Operações,3086259.0,Reais Mil,021610,2020-06-30,96054
2,6.01.01.01,Lucro Líquido do Período,1916880.0,Reais Mil,021610,2020-06-30,96054
3,6.01.01.02,Depreciação e Amortização,506140.0,Reais Mil,021610,2020-06-30,96054
4,6.01.01.03,Imposto de Renda e Contribuição Social Diferidos,189036.0,Reais Mil,021610,2020-06-30,96054

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-06-30,96054
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2020-06-30,96054
2,5.03,Saldos Iniciais Ajustados,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-06-30,96054
3,5.04,Transações de Capital com os Sócios,9000000.0,-9209319.0,-994247.0,-592802.0,0.0,-1796368.0,155.0,-1796213.0,Reais Mil,021610,2020-06-30,96054
4,5.04.01,Aumentos de Capital,9000000.0,-9000000.0,0.0,0.0,0.0,0.0,0.0,0.0,Reais Mil,021610,2020-06-30,96054

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,4306213.0,Reais Mil,021610,2020-06-30,96054
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",4254226.0,Reais Mil,021610,2020-06-30,96054
2,7.01.02,Outras Receitas,NaN,Reais Mil,021610,2020-06-30,96054
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,58635.0,Reais Mil,021610,2020-06-30,96054
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,-6648.0,Reais Mil,021610,2020-06-30,96054

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 93114 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,41141848.0,Reais Mil,021610,2020-03-31,93114
1,1.01,Ativo Circulante,11881340.0,Reais Mil,021610,2020-03-31,93114
2,1.01.01,Caixa e Equivalentes de Caixa,905064.0,Reais Mil,021610,2020-03-31,93114
3,1.01.02,Aplicações Financeiras,10070642.0,Reais Mil,021610,2020-03-31,93114
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,9642994.0,Reais Mil,021610,2020-03-31,93114

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,41141848.0,Reais Mil,021610,2020-03-31,93114
1,2.01,Passivo Circulante,9987972.0,Reais Mil,021610,2020-03-31,93114
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2020-03-31,93114
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2020-03-31,93114
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2020-03-31,93114

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,1905201.0,Reais Mil,021610,2020-03-31,93114
1,3.01.01,Segmento Listado,1505773.0,Reais Mil,021610,2020-03-31,93114
2,3.01.02,Segmento Balcão,245505.0,Reais Mil,021610,2020-03-31,93114
3,3.01.03,Segmento Infraestrutura para Financiamento,104267.0,Reais Mil,021610,2020-03-31,93114
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",269617.0,Reais Mil,021610,2020-03-31,93114

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,1025121,Reais Mil,021610,2020-03-31,93114
1,4.02,Outros Resultados Abrangentes,-25829,Reais Mil,021610,2020-03-31,93114
2,4.02.01,Variação Cambial sobre Investimento em Control...,11014,Reais Mil,021610,2020-03-31,93114
3,4.02.02,Valor dos Instrumentos de Hedges de Fluxo de C...,859,Reais Mil,021610,2020-03-31,93114
4,4.02.03,Transferência para o Resultado de Instrumento ...,-7276,Reais Mil,021610,2020-03-31,93114

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,1045723.0,Reais Mil,021610,2020-03-31,93114
1,6.01.01,Caixa Gerado nas Operações,1600716.0,Reais Mil,021610,2020-03-31,93114
2,6.01.01.01,Lucro Líquido do Período,1025121.0,Reais Mil,021610,2020-03-31,93114
3,6.01.01.02,Depreciação e Amortização,261908.0,Reais Mil,021610,2020-03-31,93114
4,6.01.01.03,Imposto de Renda e Contribuição Social Diferidos,62163.0,Reais Mil,021610,2020-03-31,93114

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-03-31,93114
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2020-03-31,93114
2,5.03,Saldos Iniciais Ajustados,3548655.0,17925964.0,3870486.0,0.0,42896.0,25388001.0,13232.0,25401233.0,Reais Mil,021610,2020-03-31,93114
3,5.04,Transações de Capital com os Sócios,9000000.0,-9215496.0,-994247.0,-292802.0,0.0,-1502545.0,90.0,-1502455.0,Reais Mil,021610,2020-03-31,93114
4,5.04.01,Aumentos de Capital,9000000.0,-9000000.0,0.0,0.0,0.0,0.0,0.0,0.0,Reais Mil,021610,2020-03-31,93114

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,2125162.0,Reais Mil,021610,2020-03-31,93114
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",2125162.0,Reais Mil,021610,2020-03-31,93114
2,7.01.02,Outras Receitas,NaN,Reais Mil,021610,2020-03-31,93114
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,NaN,Reais Mil,021610,2020-03-31,93114
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,NaN,Reais Mil,021610,2020-03-31,93114

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) - 91388 - 1 ********************
Balanço Patrimonial Ativo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,1,Ativo Total,40027315.0,Reais Mil,021610,2019-12-31,91388
1,1.01,Ativo Circulante,10469005.0,Reais Mil,021610,2019-12-31,91388
2,1.01.01,Caixa e Equivalentes de Caixa,494033.0,Reais Mil,021610,2019-12-31,91388
3,1.01.02,Aplicações Financeiras,8977000.0,Reais Mil,021610,2019-12-31,91388
4,1.01.02.01,Aplicações Financeiras Avaliadas a Valor Justo...,8407832.0,Reais Mil,021610,2019-12-31,91388

Balanço Patrimonial Passivo

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,2,Passivo Total,40027315.0,Reais Mil,021610,2019-12-31,91388
1,2.01,Passivo Circulante,8055193.0,Reais Mil,021610,2019-12-31,91388
2,2.01.01,Obrigações Sociais e Trabalhistas,NaN,Reais Mil,021610,2019-12-31,91388
3,2.01.01.01,Obrigações Sociais,NaN,Reais Mil,021610,2019-12-31,91388
4,2.01.01.02,Obrigações Trabalhistas,NaN,Reais Mil,021610,2019-12-31,91388

Demonstração do Resultado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,3.01,Receita de Venda de Bens e/ou Serviços,6576507.0,Reais Mil,021610,2019-12-31,91388
1,3.01.01,Segmento Listado,4266356.0,Reais Mil,021610,2019-12-31,91388
2,3.01.02,Segmento Balcão,991010.0,Reais Mil,021610,2019-12-31,91388
3,3.01.03,Segmento Infraestrutura para Financiamento,566378.0,Reais Mil,021610,2019-12-31,91388
4,3.01.04,"Segmento Tecnologia, Dados e Serviços",752763.0,Reais Mil,021610,2019-12-31,91388

Demonstração do Resultado Abrangente

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,4.01,Lucro Líquido Consolidado do Período,2713204,Reais Mil,021610,2019-12-31,91388
1,4.02,Outros Resultados Abrangentes,999,Reais Mil,021610,2019-12-31,91388
2,4.02.01,Variação Cambial sobre Investimento em Control...,702,Reais Mil,021610,2019-12-31,91388
3,4.02.02,Valor dos Instrumentos de Hedges de Fluxo de C...,31546,Reais Mil,021610,2019-12-31,91388
4,4.02.03,Transferência para o Resultado de Instrumento ...,-39698,Reais Mil,021610,2019-12-31,91388

Demonstração do Fluxo de Caixa

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,6.01,Caixa Líquido Atividades Operacionais,3219991.0,Reais Mil,021610,2019-12-31,91388
1,6.01.01,Caixa Gerado nas Operações,4788043.0,Reais Mil,021610,2019-12-31,91388
2,6.01.01.01,Lucro Líquido do Exercício,2713204.0,Reais Mil,021610,2019-12-31,91388
3,6.01.01.02,Depreciação e Amortização,1030250.0,Reais Mil,021610,2019-12-31,91388
4,6.01.01.03,Redução ao Valor Recuperável de Ativos,0.0,Reais Mil,021610,2019-12-31,91388

Demonstração das Mutações do Patrimônio Líquido

,Conta,Descrição,Capital Social Integralizado,"Reservas de Capital, Opções Outorgadas e Ações em Tesouraria",Reservas de Lucro,Lucros ou Prejuízos Acumulados,Outros Resultados Abrangentes,Patrimônio Líquido,Participação dos Não Controladores,Patrimônio Líquido Consolidado,currency_unit,cod_cvm,ref_date,numSequencia
0,5.01,Saldos Iniciais,3548655.0,17918974.0,3523443.0,0.0,41897.0,25032969.0,11227.0,25044196.0,Reais Mil,021610,2019-12-31,91388
1,5.02,Ajustes de Exercícios Anteriores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2019-12-31,91388
2,5.03,Saldos Iniciais Ajustados,3548655.0,17918974.0,3523443.0,0.0,41897.0,25032969.0,11227.0,25044196.0,Reais Mil,021610,2019-12-31,91388
3,5.04,Transações de Capital com os Sócios,0.0,8716.0,347043.0,-2714752.0,0.0,-2358993.0,2967.0,-2356026.0,Reais Mil,021610,2019-12-31,91388
4,5.04.01,Aumentos de Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reais Mil,021610,2019-12-31,91388

Demonstração de Valor Adicionado

,Conta,Descrição,Valor,currency_unit,cod_cvm,ref_date,numSequencia
0,7.01,Receitas,6576507.0,Reais Mil,021610,2019-12-31,91388
1,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",6576507.0,Reais Mil,021610,2019-12-31,91388
2,7.01.02,Outras Receitas,NaN,Reais Mil,021610,2019-12-31,91388
3,7.01.03,Receitas refs. à Construção de Ativos Próprios,NaN,Reais Mil,021610,2019-12-31,91388
4,7.01.04,Provisão/Reversão de Créds. Liquidação Duvidosa,NaN,Reais Mil,021610,2019-12-31,91388

In [ ]:
reports_list = [
    'Balanço Patrimonial Ativo',
    'Balanço Patrimonial Passivo',
    'Demonstração do Resultado',
    'Demonstração do Resultado Abrangente',
    'Demonstração do Fluxo de Caixa',
    'Demonstração das Mutações do Patrimônio Líquido',
    'Demonstração de Valor Adicionado']

In [ ]:
for index, row in search_result.iterrows():
    empresa = f"{row['cod_cvm']} - {cvm_codes[row['cod_cvm']]}"
    print("*" * 20, empresa, "*" * 20)
    reports = cvm_httpclient.get_report(row["numero_seq_documento"], row["codigo_tipo_instituicao"], reports_list=reports_list)
    
    for report in reports:
        reports[report]["cod_cvm"] = row["cod_cvm"]
        print(reports[report].head())

******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) ********************
        Conta                                          Descrição       Valor  \
0           1                                        Ativo Total  47594773.0
1        1.01                                   Ativo Circulante  17129613.0
2     1.01.01                      Caixa e Equivalentes de Caixa   2613794.0
3     1.01.02                             Aplicações Financeiras  12290717.0
4  1.01.02.01  Aplicações Financeiras Avaliadas a Valor Justo...  11085778.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
        Conta                          Descrição       Valor currency_unit  \
0           2                      Passivo Total  47594773.0     Reais Mil
1        2.01                 Passivo Circulante   9306446.0     Reais Mil
2     2.01.01  Obrigações Sociais e Trabalhistas         NaN     Reais Mil
3  2.01.01.01                 Obrigações Sociais         NaN     Reais Mil
4  2.01.01.02            Obrigações Trabalhistas         NaN     Reais Mil

  cod_cvm
0  021610
1  021610
2  021610
3  021610
4  021610
     Conta                                   Descrição       Valor  \
0     3.01      Receita de Venda de Bens e/ou Serviços  10110682.0
1  3.01.01                            Segmento Listado   6578577.0
2  3.01.02                             Segmento Balcão   1296363.0
3  3.01.03  Segmento Infraestrutura para Financiamento    441779.0
4  3.01.04       Segmento Tecnologia, Dados e Serviços   1789468.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
     Conta                                          Descrição    Valor  \
0     4.01               Lucro Líquido Consolidado do Período  4226598
1     4.02                      Outros Resultados Abrangentes   173586
2  4.02.01  Variação Cambial sobre Investimento em Control...    -3503
3  4.02.02  Valor dos Instrumentos de Hedge de Fluxo de Ca...   160589
4  4.02.03  Transferência de Instrumento de Hedge para o R...   -19801

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
        Conta                               Descrição      Valor  \
0        6.01   Caixa Líquido Atividades Operacionais  9887484.0
1     6.01.01              Caixa Gerado nas Operações  7085400.0
2  6.01.01.01              Lucro Líquido do Exercício  4226598.0
3  6.01.01.02               Depreciação e Amortização  1056304.0
4  6.01.01.03  Redução ao Valor Recuperável de Ativos        0.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
     Conta                            Descrição  Capital Social Integralizado  \
0     5.01                      Saldos Iniciais                    12548655.0
1     5.02     Ajustes de Exercícios Anteriores                           NaN
2     5.03            Saldos Iniciais Ajustados                    12548655.0
3     5.04  Transações de Capital com os Sócios                           0.0
4  5.04.01                  Aumentos de Capital                           NaN

   Reservas de Capital, Opções Outorgadas e Ações em Tesouraria  \
0                                          7556201.0
1                                                NaN
2                                          7556201.0
3                                         -3678067.0
4                                                NaN

   Reservas de Lucro  Lucros ou Prejuízos Acumulados  \
0          2527217.0                             0.0
1                NaN                             NaN
2          2527217.0                             0.0
3          -576705.0                      -2281639.0
4                NaN                             NaN

   Outros Resultados Abrangentes  Patrimônio Líquido  \
0                      -224168.0          22407905.0
1                            NaN                 NaN
2                      -224168.0          22407905.0
3                            0.0          -6536411.0
4                            NaN                 NaN

   Participação dos Não Controladores  Patrimônio Líquido Consolidado  \
0                             11465.0                      22419370.0
1                                 NaN                             NaN
2                             11465.0                      22419370.0
3                                 0.0                      -6536411.0
4                                 NaN                             NaN

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
     Conta                                        Descrição       Valor  \
0     7.01                                         Receitas  10181334.0
1  7.01.01       Vendas de Mercadorias, Produtos e Serviços  10106187.0
2  7.01.02                                  Outras Receitas      4495.0
3  7.01.03   Receitas refs. à Construção de Ativos Próprios     59429.0
4  7.01.04  Provisão/Reversão de Créds. Liquidação Duvidosa     11223.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) ********************
        Conta                                          Descrição       Valor  \
0           1                                        Ativo Total  47594773.0
1        1.01                                   Ativo Circulante  17129613.0
2     1.01.01                      Caixa e Equivalentes de Caixa   2613794.0
3     1.01.02                             Aplicações Financeiras  12290717.0
4  1.01.02.01  Aplicações Financeiras Avaliadas a Valor Justo...  11085778.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
        Conta                          Descrição       Valor currency_unit  \
0           2                      Passivo Total  47594773.0     Reais Mil
1        2.01                 Passivo Circulante   9306446.0     Reais Mil
2     2.01.01  Obrigações Sociais e Trabalhistas         NaN     Reais Mil
3  2.01.01.01                 Obrigações Sociais         NaN     Reais Mil
4  2.01.01.02            Obrigações Trabalhistas         NaN     Reais Mil

  cod_cvm
0  021610
1  021610
2  021610
3  021610
4  021610
     Conta                                   Descrição       Valor  \
0     3.01      Receita de Venda de Bens e/ou Serviços  10110682.0
1  3.01.01                            Segmento Listado   6578577.0
2  3.01.02                             Segmento Balcão   1296363.0
3  3.01.03  Segmento Infraestrutura para Financiamento    441779.0
4  3.01.04       Segmento Tecnologia, Dados e Serviços   1789468.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
     Conta                                          Descrição    Valor  \
0     4.01               Lucro Líquido Consolidado do Período  4226598
1     4.02                      Outros Resultados Abrangentes   173586
2  4.02.01  Variação Cambial sobre Investimento em Control...    -3503
3  4.02.02  Valor dos Instrumentos de Hedge de Fluxo de Ca...   160589
4  4.02.03  Transferência de Instrumento de Hedge para o R...   -19801

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
        Conta                               Descrição      Valor  \
0        6.01   Caixa Líquido Atividades Operacionais  9887484.0
1     6.01.01              Caixa Gerado nas Operações  7085400.0
2  6.01.01.01              Lucro Líquido do Exercício  4226598.0
3  6.01.01.02               Depreciação e Amortização  1056304.0
4  6.01.01.03  Redução ao Valor Recuperável de Ativos        0.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
     Conta                            Descrição  Capital Social Integralizado  \
0     5.01                      Saldos Iniciais                    12548655.0
1     5.02     Ajustes de Exercícios Anteriores                           NaN
2     5.03            Saldos Iniciais Ajustados                    12548655.0
3     5.04  Transações de Capital com os Sócios                           0.0
4  5.04.01                  Aumentos de Capital                           NaN

   Reservas de Capital, Opções Outorgadas e Ações em Tesouraria  \
0                                          7556201.0
1                                                NaN
2                                          7556201.0
3                                         -3678067.0
4                                                NaN

   Reservas de Lucro  Lucros ou Prejuízos Acumulados  \
0          2527217.0                             0.0
1                NaN                             NaN
2          2527217.0                             0.0
3          -576705.0                      -2281639.0
4                NaN                             NaN

   Outros Resultados Abrangentes  Patrimônio Líquido  \
0                      -224168.0          22407905.0
1                            NaN                 NaN
2                      -224168.0          22407905.0
3                            0.0          -6536411.0
4                            NaN                 NaN

   Participação dos Não Controladores  Patrimônio Líquido Consolidado  \
0                             11465.0                      22419370.0
1                                 NaN                             NaN
2                             11465.0                      22419370.0
3                                 0.0                      -6536411.0
4                                 NaN                             NaN

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
     Conta                                        Descrição       Valor  \
0     7.01                                         Receitas  10181334.0
1  7.01.01       Vendas de Mercadorias, Produtos e Serviços  10106187.0
2  7.01.02                                  Outras Receitas      4495.0
3  7.01.03   Receitas refs. à Construção de Ativos Próprios     59429.0
4  7.01.04  Provisão/Reversão de Créds. Liquidação Duvidosa     11223.0

  currency_unit cod_cvm
0     Reais Mil  021610
1     Reais Mil  021610
2     Reais Mil  021610
3     Reais Mil  021610
4     Reais Mil  021610
******************** 021610 - BRASIL, BOLSA, BALCÃO (REGISTRO ATIVO) ********************

KeyError: ignored

2. pybacen

4. Fundamentus

# Intrinio

In [ ]:
!pip install intrinio-sdk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting intrinio-sdk
  Downloading intrinio_sdk-6.23.0-py3-none-any.whl (988 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 988.4/988.4 KB 24.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from intrinio-sdk) (2.8.2)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.9/dist-packages (from intrinio-sdk) (1.16.0)
Collecting retrying>=1.3.3
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Requirement already satisfied: urllib3>=1.15 in /usr/local/lib/python3.9/dist-packages (from intrinio-sdk) (1.26.15)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from intrinio-sdk) (2022.12.7)
Installing collected packages: retrying, intrinio-sdk
Successfully installed intrinio-sdk-6.23.0 retrying-1.3.4

In [ ]:
from __future__ import print_function
import time
import intrinio_sdk as intrinio
from intrinio_sdk.rest import ApiException

intrinio.ApiClient().set_api_key('OmVmMDFiYjVhMDZjYTFkYjA4NzUyMzAyNzljZDQ2Nzcy')
intrinio.ApiClient().allow_retries(True)

In [ ]:
identifier = 'AAPL'
filed_after = ''
filed_before = ''
reported_only = False
fiscal_year = ''
statement_code = ''
type = ''
start_date = ''
end_date = ''
page_size = 100
next_page = ''

response = intrinio.CompanyApi().get_company_fundamentals(identifier, filed_after=filed_after, filed_before=filed_before, reported_only=reported_only, fiscal_year=fiscal_year, statement_code=statement_code, type=type, start_date=start_date, end_date=end_date, page_size=page_size, next_page=next_page)
print(response)

ApiException: ignored

# **3. AlphaVantage**

In [ ]:
!pip install alpha_vantage

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting alpha_vantage
  Downloading alpha_vantage-2.3.1-py3-none-any.whl (31 kB)
Collecting aiohttp
  Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 13.8 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from alpha_vantage) (2.27.1)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->alpha_vantage) (22.2.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->alpha_vantage) (2.0.12)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 14.7 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 9.6 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 18.7 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->alpha_vantage) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->alpha_vantage) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->alpha_vantage) (2022.12.7)
Installing collected packages: multidict, frozenlist, async-timeout, yarl, aiosignal, aiohttp, alpha_vantage
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 alpha_vantage-2.3.1 async-timeout-4.0.2 frozenlist-1.3.3 multidict-6.0.4 yarl-1.8.2

In [ ]:
from alpha_vantage.fundamentaldata import FundamentalData

In [ ]:

api_key ='U651A3TJS9EXCZXM'
# Define a API key para acesso aos dados
#api_key = "SUA_API_KEY_AQUI"

fd = FundamentalData(key=api_key)

In [ ]:
# Define o ticker da ação que se deseja obter os dados
ticker = "AAPL"

# Obtém as demonstrações financeiras
financials = fd.get_income_statement_annual(symbol=ticker)

In [ ]:
financials

(  fiscalDateEnding reportedCurrency   grossProfit  totalRevenue costOfRevenue  \
 0       2022-09-30              USD  170782000000  391397000000  248640000000
 1       2021-09-30              USD  152836000000  363172000000  234954000000
 2       2020-09-30              USD  104956000000  271642000000  189475000000
 3       2019-09-30              USD   98392000000  256598000000  180027000000
 4       2018-09-30              USD  101839000000  265595000000  163756000000

   costofGoodsAndServicesSold operatingIncome sellingGeneralAndAdministrative  \
 0               223546000000    119437000000                     25094000000
 1               212981000000    108949000000                     21973000000
 2               169559000000     66288000000                     19916000000
 3               161782000000     63930000000                     18245000000
 4               163756000000     70898000000                     16705000000

   researchAndDevelopment operatingExpenses  ... depreciation  \
 0            26251000000       51345000000  ...   8700000000
 1            21914000000       43887000000  ...   9500000000
 2            18752000000       38668000000  ...   9700000000
 3            16217000000       34462000000  ...  11300000000
 4            14236000000       30941000000  ...   9300000000

   depreciationAndAmortization incomeBeforeTax incomeTaxExpense  \
 0                 11104000000    119103000000      19300000000
 1                 11284000000    109207000000      14527000000
 2                 11056000000     67091000000       9680000000
 3                 12547000000     65737000000      10481000000
 4                 10903000000     72903000000      13372000000

   interestAndDebtExpense netIncomeFromContinuingOperations  \
 0             2931000000                       99803000000
 1             2645000000                       94680000000
 2             2873000000                       57411000000
 3             3576000000                       55256000000
 4             3240000000                       59531000000

   comprehensiveIncomeNetOfTax          ebit        ebitda    netIncome
 0                 88531000000  122034000000  133138000000  99803000000
 1                 95249000000  111852000000  123136000000  94680000000
 2                 57453000000   69964000000   81020000000  57411000000
 3                 58037000000   69313000000   81860000000  55256000000
 4                 56505000000   76143000000   87046000000  59531000000

 [5 rows x 26 columns], 'AAPL')

In [ ]:
financials[0]

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2022-09-30,USD,170782000000,391397000000,248640000000,223546000000,119437000000,25094000000,26251000000,51345000000,...,8700000000,11104000000,119103000000,19300000000,2931000000,99803000000,88531000000,122034000000,133138000000,99803000000
1,2021-09-30,USD,152836000000,363172000000,234954000000,212981000000,108949000000,21973000000,21914000000,43887000000,...,9500000000,11284000000,109207000000,14527000000,2645000000,94680000000,95249000000,111852000000,123136000000,94680000000
2,2020-09-30,USD,104956000000,271642000000,189475000000,169559000000,66288000000,19916000000,18752000000,38668000000,...,9700000000,11056000000,67091000000,9680000000,2873000000,57411000000,57453000000,69964000000,81020000000,57411000000
3,2019-09-30,USD,98392000000,256598000000,180027000000,161782000000,63930000000,18245000000,16217000000,34462000000,...,11300000000,12547000000,65737000000,10481000000,3576000000,55256000000,58037000000,69313000000,81860000000,55256000000
4,2018-09-30,USD,101839000000,265595000000,163756000000,163756000000,70898000000,16705000000,14236000000,30941000000,...,9300000000,10903000000,72903000000,13372000000,3240000000,59531000000,56505000000,76143000000,87046000000,59531000000

In [ ]:
# Define o ticker da ação que se deseja obter os dados
ticker = "PETR4.SAO"

# Obtém as demonstrações financeiras
financials = fd.get_income_statement_annual(symbol=ticker)

ValueError: ignored

In [ ]:
# Define o ticker da ação que se deseja obter os dados
ticker = "AMZN"

# Obtém as demonstrações financeiras
financials = fd.get_income_statement_annual(symbol=ticker)

In [ ]:
financials[0]

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2022-12-31,USD,139192000000,511276000000,372084000000,288831000000,12248000000,74729000000,73213000000,84853000000,...,24924000000,6704000000,-5939000000,-3217000000,2367000000,-2722000000,-5833000000,-3572000000,3132000000,-2722000000
1,2021-12-31,USD,126928000000,467958000000,341030000000,272344000000,24879000000,58274000000,56052000000,69686000000,...,22909000000,10412000000,38155000000,4791000000,1809000000,33355000000,32168000000,39964000000,50376000000,33364000000
2,2020-12-31,USD,102560000000,384452000000,281892000000,233307000000,22899000000,39576000000,42740000000,49985000000,...,16239000000,9009000000,24194000000,2863000000,1647000000,21331000000,22137000000,25841000000,34850000000,21331000000
3,2019-12-31,USD,67626000000,278902000000,211276000000,165536000000,14541000000,35081000000,35931000000,46941000000,...,15100000000,10659000000,13988000000,2400000000,1600000000,11588000000,11637000000,15588000000,26247000000,11588000000
4,2018-12-31,USD,65283000000,231264000000,165981000000,139156000000,12421000000,26350000000,28837000000,27999000000,...,12138000000,475000000,11270000000,1197000000,1417000000,10073000000,9526000000,12687000000,13162000000,10073000000

In [ ]:
# Obtém os indicadores de valuation
metrics = fd.get_key_metrics_annual(symbol=ticker)

AttributeError: ignored

In [ ]:
metrics

In [ ]:
# Obtém os dados de dividendos
dividends = fd.get_dividends(symbol=ticker)

AttributeError: ignored

# **5. Finnhub**

Descrição do que é pago e do que é gratuito

https://finnhub.io/docs/api/financials-reported

In [ ]:
!pip install finnhub-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting finnhub-python
  Downloading finnhub_python-2.4.16-py3-none-any.whl (11 kB)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.9/dist-packages (from finnhub-python) (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->finnhub-python) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->finnhub-python) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->finnhub-python) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->finnhub-python) (2.0.12)
Installing collected packages: finnhub-python
Successfully installed finnhub-python-2.4.16

In [ ]:
import finnhub

# Define a API key para acesso aos dados
finnhub_client = finnhub.Client(api_key="cgeaj8hr01qvduhgk9p0cgeaj8hr01qvduhgk9pg")

In [ ]:
# Define o ticker da ação que se deseja obter os dados
ticker = "AAPL"

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(finnhub_client.company_basic_financials('AAPL', 'all'))

,metric,metricType,series,symbol
10DayAverageTradingVolume,72.38708,perShare,NaN,AAPL
13WeekPriceReturnDaily,15.23307,perShare,NaN,AAPL
26WeekPriceReturnDaily,2.85335,perShare,NaN,AAPL
3MonthAverageTradingVolume,1448.3712,perShare,NaN,AAPL
52WeekHigh,179.61,perShare,NaN,AAPL
...,...,...,...,...
totalDebt/totalEquityAnnual,238.8104,perShare,NaN,AAPL
totalDebt/totalEquityQuarterly,195.8679,perShare,NaN,AAPL
yearToDatePriceReturnDaily,19.29501,perShare,NaN,AAPL
annual,NaN,perShare,"{'bookValue': [{'period': '2022-09-24', 'v': 5...",AAPL
quarterly,NaN,perShare,"{'bookValue': [{'period': '2022-12-31', 'v': 5...",AAPL

In [ ]:
list(pd.DataFrame(finnhub_client.company_basic_financials('AAPL', 'all')).index)

['10DayAverageTradingVolume',
 '13WeekPriceReturnDaily',
 '26WeekPriceReturnDaily',
 '3MonthAverageTradingVolume',
 '52WeekHigh',
 '52WeekHighDate',
 '52WeekLow',
 '52WeekLowDate',
 '52WeekPriceReturnDaily',
 '5DayPriceReturnDaily',
 'assetTurnoverAnnual',
 'assetTurnoverTTM',
 'beta',
 'bookValuePerShareAnnual',
 'bookValuePerShareQuarterly',
 'bookValueShareGrowth5Y',
 'capitalSpendingGrowth5Y',
 'cashFlowPerShareAnnual',
 'cashFlowPerShareTTM',
 'cashPerSharePerShareAnnual',
 'cashPerSharePerShareQuarterly',
 'currentDividendYieldTTM',
 'currentEv/freeCashFlowAnnual',
 'currentEv/freeCashFlowTTM',
 'currentRatioAnnual',
 'currentRatioQuarterly',
 'dividendGrowthRate5Y',
 'dividendPerShare5Y',
 'dividendPerShareAnnual',
 'dividendYield5Y',
 'dividendYieldIndicatedAnnual',
 'dividendsPerShareTTM',
 'ebitdPerShareTTM',
 'ebitdaCagr5Y',
 'ebitdaInterimCagr5Y',
 'epsBasicExclExtraItemsAnnual',
 'epsBasicExclExtraItemsTTM',
 'epsExclExtraItemsAnnual',
 'epsExclExtraItemsTTM',
 'epsGrowth3Y',
 'epsGrowth5Y',
 'epsGrowthQuarterlyYoy',
 'epsGrowthTTMYoy',
 'epsInclExtraItemsAnnual',
 'epsInclExtraItemsTTM',
 'epsNormalizedAnnual',
 'focfCagr5Y',
 'grossMargin5Y',
 'grossMarginAnnual',
 'grossMarginTTM',
 'inventoryTurnoverAnnual',
 'inventoryTurnoverTTM',
 'longTermDebt/equityAnnual',
 'longTermDebt/equityQuarterly',
 'marketCapitalization',
 'monthToDatePriceReturnDaily',
 'netIncomeEmployeeAnnual',
 'netIncomeEmployeeTTM',
 'netInterestCoverageAnnual',
 'netInterestCoverageTTM',
 'netMarginGrowth5Y',
 'netProfitMargin5Y',
 'netProfitMarginAnnual',
 'netProfitMarginTTM',
 'operatingMargin5Y',
 'operatingMarginAnnual',
 'operatingMarginTTM',
 'payoutRatioAnnual',
 'payoutRatioTTM',
 'pbAnnual',
 'pbQuarterly',
 'pcfShareTTM',
 'peBasicExclExtraTTM',
 'peExclExtraAnnual',
 'peExclExtraTTM',
 'peInclExtraTTM',
 'peNormalizedAnnual',
 'pfcfShareAnnual',
 'pfcfShareTTM',
 'pretaxMargin5Y',
 'pretaxMarginAnnual',
 'pretaxMarginTTM',
 'priceRelativeToS&P50013Week',
 'priceRelativeToS&P50026Week',
 'priceRelativeToS&P5004Week',
 'priceRelativeToS&P500Ytd',
 'psAnnual',
 'psTTM',
 'ptbvAnnual',
 'ptbvQuarterly',
 'quickRatioAnnual',
 'receivablesTurnoverAnnual',
 'receivablesTurnoverTTM',
 'revenueEmployeeAnnual',
 'revenueEmployeeTTM',
 'revenueGrowth3Y',
 'revenueGrowth5Y',
 'revenueGrowthQuarterlyYoy',
 'revenueGrowthTTMYoy',
 'revenuePerShareAnnual',
 'revenuePerShareTTM',
 'revenueShareGrowth5Y',
 'roaRfy',
 'roaa5Y',
 'roae5Y',
 'roaeTTM',
 'roeRfy',
 'roeTTM',
 'roi5Y',
 'roiAnnual',
 'roiTTM',
 'tangibleBookValuePerShareAnnual',
 'tangibleBookValuePerShareQuarterly',
 'tbvCagr5Y',
 'totalDebt/totalEquityAnnual',
 'totalDebt/totalEquityQuarterly',
 'yearToDatePriceReturnDaily',
 'annual',
 'quarterly']

In [ ]:
newdata = pd.DataFrame(finnhub_client.company_basic_financials('AAPL', 'all'))

In [ ]:
newdata.loc['revenuePerShareAnnual']

metric        24.15364
metricType    perShare
series             NaN
symbol            AAPL
Name: revenuePerShareAnnual, dtype: object

In [ ]:
# Obtém as demonstrações financeiras
financials = finnhub_client.financials(ticker, statement="bs", freq = 'quarterly')

FinnhubAPIException: ignored

In [ ]:
# Obtém os indicadores de valuation
metrics = finnhub_client.company_basic_financials(ticker, "all")

In [ ]:
metrics

{'metric': {'10DayAverageTradingVolume': 72.38708,
  '13WeekPriceReturnDaily': 15.23307,
  '26WeekPriceReturnDaily': 2.85335,
  '3MonthAverageTradingVolume': 1448.3712,
  '52WeekHigh': 179.61,
  '52WeekHighDate': '2022-03-30',
  '52WeekLow': 124.18,
  '52WeekLowDate': '2023-01-03',
  '52WeekPriceReturnDaily': -3.49894,
  '5DayPriceReturnDaily': 4.3771,
  'assetTurnoverAnnual': 1.12064,
  'assetTurnoverTTM': 1.06475,
  'beta': 1.28223,
  'bookValuePerShareAnnual': 3.17824,
  'bookValuePerShareQuarterly': 3.58071,
  'bookValueShareGrowth5Y': -13.43208,
  'capitalSpendingGrowth5Y': -2.97116,
  'cashFlowPerShareAnnual': 6.79335,
  'cashFlowPerShareTTM': 6.57983,
  'cashPerSharePerShareAnnual': 3.02971,
  'cashPerSharePerShareQuarterly': 3.24162,
  'currentDividendYieldTTM': 0.5871,
  'currentEv/freeCashFlowAnnual': 29.58255,
  'currentEv/freeCashFlowTTM': 31.43142,
  'currentRatioAnnual': 0.87936,
  'currentRatioQuarterly': 0.93802,
  'dividendGrowthRate5Y': 6.26585,
  'dividendPerShare5Y': 0.795,
  'dividendPerShareAnnual': 0.9,
  'dividendYield5Y': 0.76329,
  'dividendYieldIndicatedAnnual': 0.59355,
  'dividendsPerShareTTM': 0.91,
  'ebitdPerShareTTM': 7.74103,
  'ebitdaCagr5Y': 13.03462,
  'ebitdaInterimCagr5Y': 11.05332,
  'epsBasicExclExtraItemsAnnual': 6.15461,
  'epsBasicExclExtraItemsTTM': 5.91936,
  'epsExclExtraItemsAnnual': 6.1132,
  'epsExclExtraItemsTTM': 5.88584,
  'epsGrowth3Y': 27.18424,
  'epsGrowth5Y': 21.57502,
  'epsGrowthQuarterlyYoy': -10.31607,
  'epsGrowthTTMYoy': -2.28133,
  'epsInclExtraItemsAnnual': 6.1132,
  'epsInclExtraItemsTTM': 5.88584,
  'epsNormalizedAnnual': 6.1132,
  'focfCagr5Y': 0.90498,
  'grossMargin5Y': 40.29693,
  'grossMarginAnnual': 43.30963,
  'grossMarginTTM': 43.05937,
  'inventoryTurnoverAnnual': 38.78987,
  'inventoryTurnoverTTM': 34.7615,
  'longTermDebt/equityAnnual': 196.8957,
  'longTermDebt/equityQuarterly': 175.6254,
  'marketCapitalization': 2452402,
  'monthToDatePriceReturnDaily': 5.1489,
  'netIncomeEmployeeAnnual': 627691.8,
  'netIncomeEmployeeTTM': 580311,
  'netInterestCoverageAnnual': 1126.764,
  'netInterestCoverageTTM': 578.5026,
  'netMarginGrowth5Y': 3.71269,
  'netProfitMargin5Y': 23.59486,
  'netProfitMarginAnnual': 25.30964,
  'netProfitMarginTTM': 24.55791,
  'operatingMargin5Y': 27.52461,
  'operatingMarginAnnual': 30.28874,
  'operatingMarginTTM': 29.40751,
  'payoutRatioAnnual': 14.8222,
  'payoutRatioTTM': 15.59299,
  'pbAnnual': 48.76916,
  'pbQuarterly': 43.28755,
  'pcfShareTTM': 23.02854,
  'peBasicExclExtraTTM': 21.95001,
  'peExclExtraAnnual': 25.35497,
  'peExclExtraTTM': 26.33439,
  'peInclExtraTTM': 26.33439,
  'peNormalizedAnnual': 25.35497,
  'pfcfShareAnnual': 25.38665,
  'pfcfShareTTM': 29.68255,
  'pretaxMargin5Y': 27.81549,
  'pretaxMarginAnnual': 30.20404,
  'pretaxMarginTTM': 29.28366,
  'priceRelativeToS&P50013Week': 13.34186,
  'priceRelativeToS&P50026Week': 8.69797,
  'priceRelativeToS&P5004Week': 5.82033,
  'priceRelativeToS&P500Ytd': 16.94544,
  'psAnnual': 6.21919,
  'psTTM': 6.32817,
  'ptbvAnnual': 48.39757,
  'ptbvQuarterly': 43.23165,
  'quickRatioAnnual': 0.84724,
  'receivablesTurnoverAnnual': 14.48085,
  'receivablesTurnoverTTM': 14.36253,
  'revenueEmployeeAnnual': 2480050,
  'revenueEmployeeTTM': 2363031,
  'revenueGrowth3Y': 14.86768,
  'revenueGrowth5Y': 11.45915,
  'revenueGrowthQuarterlyYoy': -5.47904,
  'revenueGrowthTTMYoy': 2.43549,
  'revenuePerShareAnnual': 24.15364,
  'revenuePerShareTTM': 23.94432,
  'revenueShareGrowth5Y': 17.22293,
  'roaRfy': 28.36292,
  'roaa5Y': 21.12137,
  'roae5Y': 87.99243,
  'roaeTTM': 147.943,
  'roeRfy': 175.4593,
  'roeTTM': 26.14811,
  'roi5Y': 31.65106,
  'roiAnnual': 47.04427,
  'roiTTM': 42.95903,
  'tangibleBookValuePerShareAnnual': 3.17824,
  'tangibleBookValuePerShareQuarterly': 3.58071,
  'tbvCagr5Y': -17.6806,
  'totalDebt/totalEquityAnnual': 238.8104,
  'totalDebt/totalEquityQuarterly': 195.8679,
  'yearToDatePriceReturnDaily': 19.29501},
 'metricType': 'perShare',
 'series': {'annual': {'bookValue': [{'period': '2022-09-24', 'v': 50672},
    {'period': '2021-09-25', 'v': 63090},
    {'period': '2020-09-26', 'v': 65339},
    {'period': '2019-09-28', 'v': 90488},
    {'period': '2018-09-29', 'v': 107147},
    {'period': '2017-09-30', 'v': 134047},
    {'period': '2016-09-24', 'v': 128249},
    {'period': '2015-09-26', 'v': 119355},
    {'period': '2014-09-27', 'v': 111547},
    {'period': '2013-09-28', 'v': 123549},
    {'period': '2012-09-29', 'v': 118210},
    {'period': '2011-09-24', 'v': 76615},
    {'period': '2010-09-25', 'v': 47791},
    {'period': '2009-09-26', 'v': 31640},
    {'period': '2008-09-27', 'v': 22297},
    {'period': '2007-09-29', 'v': 14532},
    {'period': '2006-09-30', 'v': 9984},
    {'period': '2005-09-24', 'v': 7428},
    {'period': '2004-09-25', 'v': 5076},
    {'period': '2003-09-27', 'v': 4223},
    {'period': '2002-09-28', 'v': 4095},
    {'period': '2001-09-29', 'v': 3920},
    {'period': '2000-09-30', 'v': 4107}],
   'cashRatio': [{'period': '2022-09-24', 'v': 0.15356340351469652},
    {'period': '2021-09-25', 'v': 0.2784485300563432},
    {'period': '2020-09-26', 'v': 0.36071049035979963},
    {'period': '2019-09-28', 'v': 0.46202160464632325},
    {'period': '2018-09-29', 'v': 0.22352474359306126},
    {'period': '2017-09-30', 'v': 0.2012518102644474},
    {'period': '2016-09-24', 'v': 0.2592714477381465},
    {'period': '2015-09-26', 'v': 0.2620022329735765},
    {'period': '2014-09-27', 'v': 0.21819442693229102},
    {'period': '2013-09-28', 'v': 0.3266068074579688},
    {'period': '2012-09-29', 'v': 0.27881272378184835},
    {'period': '2011-09-24', 'v': 0.35091169109760456},
    {'period': '2010-09-25', 'v': 0.5434321011485378},
    {'period': '2009-09-26', 'v': 0.45741352337910657},
    {'period': '2008-09-27', 'v': 1.045242496259132},
    {'period': '2007-09-29', 'v': 1.0077586206896552},
    {'period': '2006-09-30', 'v': 0.9920844327176781},
    {'period': '2005-09-24', 'v': 1.0011471178663607},
    {'period': '2004-09-25', 'v': 1.119954734062618},
    {'period': '2003-09-27', 'v': 1.4408145948239288},
    {'period': '2002-09-28', 'v': 1.3582629674306392},
    {'period': '2001-09-29', 'v': 1.5217391304347827},
    {'period': '2000-09-30', 'v': 0.6161407139161924}],
   'currentRatio': [{'period': '2022-09-24', 'v': 0.8794},
    {'period': '2021-09-25', 'v': 1.0746},
    {'period': '2020-09-26', 'v': 1.3636},
    {'period': '2019-09-28', 'v': 1.5401},
    {'period': '2018-09-29', 'v': 1.1329},
    {'period': '2017-09-30', 'v': 1.2761},
    {'period': '2016-09-24', 'v': 1.3527},
    {'period': '2015-09-26', 'v': 1.1088},
    {'period': '2014-09-27', 'v': 1.0801},
    {'period': '2013-09-28', 'v': 1.6786},
    {'period': '2012-09-29', 'v': 1.4958},
    {'period': '2011-09-24', 'v': 1.6084},
    {'period': '2010-09-25', 'v': 2.0113},
    {'period': '2009-09-26', 'v': 2.7425},
    {'period': '2008-09-27', 'v': 2.6411},
    {'period': '2007-09-29', 'v': 2.3659},
    {'period': '2006-09-30', 'v': 2.2519},
    {'period': '2005-09-24', 'v': 2.9538},
    {'period': '2004-09-25', 'v': 2.6613},
    {'period': '2003-09-27', 'v': 2.4977},
    {'period': '2002-09-28', 'v': 3.2497},
    {'period': '2001-09-29', 'v': 3.388},
    {'period': '2000-09-30', 'v': 2.8076}],
   'ebitPerShare': [{'period': '2022-09-24', 'v': 7.3158},
    {'period': '2021-09-25', 'v': 6.4601},
    {'period': '2020-09-26', 'v': 3.7818},
    {'period': '2019-09-28', 'v': 3.4378},
    {'period': '2018-09-29', 'v': 3.5449},
    {'period': '2017-09-30', 'v': 2.9202},
    {'period': '2016-09-24', 'v': 2.7282},
    {'period': '2015-09-26', 'v': 3.074},
    {'period': '2014-09-27', 'v': 2.1438},
    {'period': '2013-09-28', 'v': 1.8784},
    {'period': '2012-09-29', 'v': 2.087},
    {'period': '2011-09-24', 'v': 1.2884},
    {'period': '2010-09-25', 'v': 0.7101},
    {'period': '2009-09-26', 'v': 0.4623},
    {'period': '2008-09-27', 'v': 0.3297},
    {'period': '2007-09-29', 'v': 0.177},
    {'period': '2006-09-30', 'v': 0.0998},
    {'period': '2005-09-24', 'v': 0.0685},
    {'period': '2004-09-25', 'v': 0.0144},
    {'period': '2003-09-27', 'v': 0},
    {'period': '2002-09-28', 'v': 0.0008},
    {'period': '2001-09-29', 'v': -0.0178},
    {'period': '2000-09-30', 'v': 0.0259}],
   'eps': [{'period': '2022-09-24', 'v': 6.1132},
    {'period': '2021-09-25', 'v': 5.614},
    {'period': '2020-09-26', 'v': 3.2754},
    {'period': '2019-09-28', 'v': 2.9714},
    {'period': '2018-09-29', 'v': 2.9766},
    {'period': '2017-09-30', 'v': 2.3017},
    {'period': '2016-09-24', 'v': 2.0766},
    {'period': '2015-09-26', 'v': 2.3042},
    {'period': '2014-09-27', 'v': 1.6132},
    {'period': '2013-09-28', 'v': 1.4198},
    {'period': '2012-09-29', 'v': 1.5767},
    {'period': '2011-09-24', 'v': 0.9884},
    {'period': '2010-09-25', 'v': 0.5412},
    {'period': '2009-09-26', 'v': 0.3243},
    {'period': '2008-09-27', 'v': 0.2422},
    {'period': '2007-09-29', 'v': 0.1404},
    {'period': '2006-09-30', 'v': 0.0809},
    {'period': '2005-09-24', 'v': 0.0553},
    {'period': '2004-09-25', 'v': 0.0123},
    {'period': '2003-09-27', 'v': 0.0034},
    {'period': '2002-09-28', 'v': 0.0032},
    {'period': '2001-09-29', 'v': -0.0013},
    {'period': '2000-09-30', 'v': 0.039}],
   'ev': [{'period': '2022-09-24', 'v': 2514884},
    {'period': '2021-09-25', 'v': 2493617},
    {'period': '2020-09-26', 'v': 2041191},
    {'period': '2019-09-28', 'v': 1071363},
    {'period': '2018-09-29', 'v': 1186220},
    {'period': '2017-09-30', 'v': 889855},
    {'period': '2016-09-24', 'v': 674795},
    {'period': '2015-09-26', 'v': 670483},
    {'period': '2014-09-27', 'v': 608712},
    {'period': '2013-09-28', 'v': 435827},
    {'period': '2012-09-29', 'v': 607370},
    {'period': '2011-09-24', 'v': 364842},
    {'period': '2010-09-25', 'v': 254736},
    {'period': '2009-09-26', 'v': 161495},
    {'period': '2008-09-27', 'v': 81372.3},
    {'period': '2007-09-29', 'v': 126607},
    {'period': '2006-09-30', 'v': 57277},
    {'period': '2005-09-24', 'v': 41187},
    {'period': '2004-09-25', 'v': 11589.8},
    {'period': '2003-09-27', 'v': 4629.27},
    {'period': '2002-09-28', 'v': 3267.85},
    {'period': '2001-09-29', 'v': 3384.29},
    {'period': '2000-09-30', 'v': 6989.5}],
   'fcfMargin': [{'period': '2022-09-24', 'v': 0.3369},
    {'period': '2021-09-25', 'v': 0.3147},
    {'period': '2020-09-26', 'v': 0.3205},
    {'period': '2019-09-28', 'v': 0.307},
    {'period': '2018-09-29', 'v': 0.3417},
    {'period': '2017-09-30', 'v': 0.3345},
    {'period': '2016-09-24', 'v': 0.3662},
    {'period': '2015-09-26', 'v': 0.3969},
    {'period': '2014-09-27', 'v': 0.3803},
    {'period': '2013-09-28', 'v': 0.3671},
    {'period': '2012-09-29', 'v': 0.385},
    {'period': '2011-09-24', 'v': 0.4155},
    {'period': '2010-09-25', 'v': 0.3176},
    {'period': '2009-09-26', 'v': 0.2651},
    {'period': '2008-09-27', 'v': 0.2879},
    {'period': '2007-09-29', 'v': 0.2627},
    {'period': '2006-09-30', 'v': 0.149},
    {'period': '2005-09-24', 'v': 0.2006},
    {'period': '2004-09-25', 'v': 0.1341},
    {'period': '2003-09-27', 'v': 0.073},
    {'period': '2002-09-28', 'v': 0.0458},
    {'period': '2001-09-29', 'v': 0.0778},
    {'period': '2000-09-30', 'v': 0.1265}],
   'grossMargin': [{'period': '2022-09-24', 'v': 0.4331},
    {'period': '2021-09-25', 'v': 0.4178},
    {'period': '2020-09-26', 'v': 0.3823},
    {'period': '2019-09-28', 'v': 0.3782},
    {'period': '2018-09-29', 'v': 0.3834},
    {'period': '2017-09-30', 'v': 0.3847},
    {'period': '2016-09-24', 'v': 0.3908},
    {'period': '2015-09-26', 'v': 0.4006},
    {'period': '2014-09-27', 'v': 0.3859},
    {'period': '2013-09-28', 'v': 0.3762},
    {'period': '2012-09-29', 'v': 0.4387},
    {'period': '2011-09-24', 'v': 0.4048},
    {'period': '2010-09-25', 'v': 0.3938},
    {'period': '2009-09-26', 'v': 0.4014},
    {'period': '2008-09-27', 'v': 0.352},
    {'period': '2007-09-29', 'v': 0.3317},
    {'period': '2006-09-30', 'v': 0.2898},
    {'period': '2005-09-24', 'v': 0.2901},
    {'period': '2004-09-25', 'v': 0.2726},
    {'period': '2003-09-27', 'v': 0.2752},
    {'period': '2002-09-28', 'v': 0.2792},
    {'period': '2001-09-29', 'v': 0.2303},
    {'period': '2000-09-30', 'v': 0.2713}],
   'longtermDebtTotalAsset': [{'period': '2022-09-24', 'v': 0.2805},
    {'period': '2021-09-25', 'v': 0.3108},
    {'period': '2020-09-26', 'v': 0.3046},
    {'period': '2019-09-28', 'v': 0.2712},
    {'period': '2018-09-29', 'v': 0.2563},
    {'period': '2017-09-30', 'v': 0.259},
    {'period': '2016-09-24', 'v': 0.2345},
    {'period': '2015-09-26', 'v': 0.1837},
    {'period': '2014-09-27', 'v': 0.125},
    {'period': '2013-09-28', 'v': 0.0819},
    {'period': '2012-09-29', 'v': 0},
    {'period': '2011-09-24', 'v': 0},
    {'period': '2010-09-25', 'v': 0},
    {'period': '2009-09-26', 'v': 0},
    {'period': '2008-09-27', 'v': 0},
    {'period': '2007-09-29', 'v': 0},
    {'period': '2006-09-30', 'v': 0},
    {'period': '2005-09-24', 'v': 0},
    {'period': '2004-09-25', 'v': 0},
    {'period': '2003-09-27', 'v': 0},
    {'period': '2002-09-28', 'v': 0.0502},
    {'period': '2001-09-29', 'v': 0.0526},
    {'period': '2000-09-30', 'v': 0.0441}],
   'longtermDebtTotalCapital': [{'period': '2022-09-24', 'v': 0.5764},
    {'period': '2021-09-25', 'v': 0.5783},
    {'period': '2020-09-26', 'v': 0.553},
    {'period': '2019-09-28', 'v': 0.4624},
    {'period': '2018-09-29', 'v': 0.4229},
    {'period': '2017-09-30', 'v': 0.3893},
    {'period': '2016-09-24', 'v': 0.3504},
    {'period': '2015-09-26', 'v': 0.2903},
    {'period': '2014-09-27', 'v': 0.1974},
    {'period': '2013-09-28', 'v': 0.1207},
    {'period': '2012-09-29', 'v': 0},
    {'period': '2011-09-24', 'v': 0},
    {'period': '2010-09-25', 'v': 0},
    {'period': '2009-09-26', 'v': 0},
    {'period': '2008-09-27', 'v': 0},
    {'period': '2007-09-29', 'v': 0},
    {'period': '2006-09-30', 'v': 0},
    {'period': '2005-09-24', 'v': 0},
    {'period': '2004-09-25', 'v': 0},
    {'period': '2003-09-27', 'v': 0},
    {'period': '2002-09-28', 'v': 0.0716},
    {'period': '2001-09-29', 'v': 0.0748},
    {'period': '2000-09-30', 'v': 0.0681}],
   'longtermDebtTotalEquity': [{'period': '2022-09-24', 'v': 1.9529},
    {'period': '2021-09-25', 'v': 1.7294},
    {'period': '2020-09-26', 'v': 1.5101},
    {'period': '2019-09-28', 'v': 1.0146},
    {'period': '2018-09-29', 'v': 0.8748},
    {'period': '2017-09-30', 'v': 0.7252},
    {'period': '2016-09-24', 'v': 0.5881},
    {'period': '2015-09-26', 'v': 0.4468},
    {'period': '2014-09-27', 'v': 0.2599},
    {'period': '2013-09-28', 'v': 0.1373},
    {'period': '2012-09-29', 'v': 0},
    {'period': '2011-09-24', 'v': 0},
    {'period': '2010-09-25', 'v': 0},
    {'period': '2009-09-26', 'v': 0},
    {'period': '2008-09-27', 'v': 0},
    {'period': '2007-09-29', 'v': 0},
    {'period': '2006-09-30', 'v': 0},
    {'period': '2005-09-24', 'v': 0},
    {'period': '2004-09-25', 'v': 0},
    {'period': '2003-09-27', 'v': 0},
    {'period': '2002-09-28', 'v': 0.0772},
    {'period': '2001-09-29', 'v': 0.0809},
    {'period': '2000-09-30', 'v': 0.073}],
   'netDebtToTotalCapital': [{'period': '2022-09-24', 'v': 0.5671},
    {'period': '2021-09-25', 'v': 0.4804},
    {'period': '2020-09-26', 'v': 0.4208},
    {'period': '2019-09-28', 'v': 0.2982},
    {'period': '2018-09-29', 'v': 0.3996},
    {'period': '2017-09-30', 'v': 0.382},
    {'period': '2016-09-24', 'v': 0.3091},
    {'period': '2015-09-26', 'v': 0.2352},
    {'period': '2014-09-27', 'v': 0.1461},
    {'period': '2013-09-28', 'v': 0.0192},
    {'period': '2012-09-29', 'v': -0.0909},
    {'period': '2011-09-24', 'v': -0.1281},
    {'period': '2010-09-25', 'v': -0.2356},
    {'period': '2009-09-26', 'v': -0.1663},
    {'period': '2008-09-27', 'v': -0.5326},
    {'period': '2007-09-29', 'v': -0.6435},
    {'period': '2006-09-30', 'v': -0.6402},
    {'period': '2005-09-24', 'v': -0.47},
    {'period': '2004-09-25', 'v': -0.5849},
    {'period': '2003-09-27', 'v': -0.683},
    {'period': '2002-09-28', 'v': -0.4389},
    {'period': '2001-09-29', 'v': -0.4704},
    {'period': '2000-09-30', 'v': -0.2022}],
   'netDebtToTotalEquity': [{'period': '2022-09-24', 'v': 1.9215},
    {'period': '2021-09-25', 'v': 1.4365},
    {'period': '2020-09-26', 'v': 1.1491},
    {'period': '2019-09-28', 'v': 0.6543},
    {'period': '2018-09-29', 'v': 0.8266},
    {'period': '2017-09-30', 'v': 0.7116},
    {'period': '2016-09-24', 'v': 0.5189},
    {'period': '2015-09-26', 'v': 0.362},
    {'period': '2014-09-27', 'v': 0.1923},
    {'period': '2013-09-28', 'v': 0.0219},
    {'period': '2012-09-29', 'v': -0.0909},
    {'period': '2011-09-24', 'v': -0.1281},
    {'period': '2010-09-25', 'v': -0.2356},
    {'period': '2009-09-26', 'v': -0.1663},
    {'period': '2008-09-27', 'v': -0.5326},
    {'period': '2007-09-29', 'v': -0.6435},
    {'period': '2006-09-30', 'v': -0.6402},
    {'period': '2005-09-24', 'v': -0.47},
    {'period': '2004-09-25', 'v': -0.5849},
    {'period': '2003-09-27', 'v': -0.7322},
    {'period': '2002-09-28', 'v': -0.4728},
    {'period': '2001-09-29', 'v': -0.5084},
    {'period': '2000-09-30', 'v': -0.2169}],
   'netMargin': [{'period': '2022-09-24', 'v': 0.2531},
    {'period': '2021-09-25', 'v': 0.2588},
    {'period': '2020-09-26', 'v': 0.2091},
    {'period': '2019-09-28', 'v': 0.2124},
    {'period': '2018-09-29', 'v': 0.2241},
    {'period': '2017-09-30', 'v': 0.2109},
    {'period': '2016-09-24', 'v': 0.2119},
    {'period': '2015-09-26', 'v': 0.2285},
    {'period': '2014-09-27', 'v': 0.2161},
    {'period': '2013-09-28', 'v': 0.2167},
    {'period': '2012-09-29', 'v': 0.2667},
    {'period': '2011-09-24', 'v': 0.2395},
    {'period': '2010-09-25', 'v': 0.2148},
    {'period': '2009-09-26', 'v': 0.1919},
    {'period': '2008-09-27', 'v': 0.1632},
    {'period': '2007-09-29', 'v': 0.1422},
    {'period': '2006-09-30', 'v': 0.103},
    {'period': '2005-09-24', 'v': 0.0953},
    {'period': '2004-09-25', 'v': 0.0321},
    {'period': '2003-09-27', 'v': 0.0111},
    {'period': '2002-09-28', 'v': 0.0113},
    {'period': '2001-09-29', 'v': -0.0047},
    {'period': '2000-09-30', 'v': 0.0985}],
   'operatingMargin': [{'period': '2022-09-24', 'v': 0.3029},
    {'period': '2021-09-25', 'v': 0.2978},
    {'period': '2020-09-26', 'v': 0.2415},
    {'period': '2019-09-28', 'v': 0.2457},
    {'period': '2018-09-29', 'v': 0.2669},
    {'period': '2017-09-30', 'v': 0.2676},
    {'period': '2016-09-24', 'v': 0.2784},
    {'period': '2015-09-26', 'v': 0.3048},
    {'period': '2014-09-27', 'v': 0.2872},
    {'period': '2013-09-28', 'v': 0.2867},
    {'period': '2012-09-29', 'v': 0.353},
    {'period': '2011-09-24', 'v': 0.3122},
    {'period': '2010-09-25', 'v': 0.2819},
    {'period': '2009-09-26', 'v': 0.2736},
    {'period': '2008-09-27', 'v': 0.2221},
    {'period': '2007-09-29', 'v': 0.1793},
    {'period': '2006-09-30', 'v': 0.127},
    {'period': '2005-09-24', 'v': 0.1179},
    {'period': '2004-09-25', 'v': 0.0378},
    {'period': '2003-09-27', 'v': -0.0002},
    {'period': '2002-09-28', 'v': 0.003},
    {'period': '2001-09-29', 'v': -0.0641},
    {'period': '2000-09-30', 'v': 0.0654}],
   'pb': [{'period': '2022-09-24', 'v': 47.7092},
    {'period': '2021-09-25', 'v': 38.0883},
    {'period': '2020-09-26', 'v': 30.0909},
    {'period': '2019-09-28', 'v': 11.1856},
    {'period': '2018-09-29', 'v': 10.2443},
    {'period': '2017-09-30', 'v': 5.9268},
    {'period': '2016-09-24', 'v': 4.7427},
    {'period': '2015-09-26', 'v': 5.2555},
    {'period': '2014-09-27', 'v': 5.2647},
    {'period': '2013-09-28', 'v': 3.5057},
    {'period': '2012-09-29', 'v': 5.229},
    {'period': '2011-09-24', 'v': 4.8901},
    {'period': '2010-09-25', 'v': 5.5658},
    {'period': '2009-09-26', 'v': 5.2705},
    {'period': '2008-09-27', 'v': 4.1821},
    {'period': '2007-09-29', 'v': 9.3558},
    {'period': '2006-09-30', 'v': 6.3771},

In [ ]:
# Obtém os dados de dividendos
dividends = finnhub_client.dividends(ticker, _from="2021-01-01", to="2022-01-01")

AttributeError: ignored

In [ ]:

# Imprime os resultados
print(financials)
print(metrics)
print(dividends)

NameError: ignored